---

sap_install_media_detect_rar_package: ''

# commands for handling rar files
sap_install_media_detect_rar_list: '/usr/bin/lsar'
sap_install_media_detect_rar_extract: '/usr/bin/unar'

#sap_install_media_detect_rar_list: '/usr/bin/unrar lb'
#sap_install_media_detect_rar_extract: '/usr/bin/unrar x'

# e.g. /software
sap_install_media_detect_directory:

# local_dir, remote_dir (e.g. NFS, s3fuse)
sap_install_media_detect_source: local_dir

# saphana, sapase, sapmaxdb, oracledb, ibmdb2
sap_install_media_detect_db: "saphana"

sap_install_media_detect_swpm: true
sap_install_media_detect_hostagent: true
sap_install_media_detect_igs: true
sap_install_media_detect_kernel: true
sap_install_media_detect_webdisp: false

# saps4hana, sapecc, sapecc_ides, sapbw4hana, sapnwas_abap, sapnwas_java
sap_install_media_detect_export:

# e.g. /db_backup
sap_install_media_detect_backup_directory:

# saphana
sap_install_media_detect_backup:
