---
# tasks file for update_etc_hosts
- name: Ensure required defaults are read from setup module
  when: >
    not ((ansible_hostname is defined) and
    (ansible_domain is defined) and
    (ansible_default_ipv4 is defined))
  ## the above resolves to, but the above is said to be more reliable - should be tested later
  # (ansible_hostname is undefined) or
  # (ansible_domain is undefined) or
  # (ansible_default_ipv4 is defined)
  ansible.builtin.setup:
    gather_subset: "{{ __update_etc_hosts_gather_subset }}"
    filter:
      - 'ansible_hostname'
      - 'ansible_domain'
      - 'ansible_default_ipv4'

# TODO: Double Check that list entries with state present do not have duplicate IP adresses

- name: Add entry to "{{ __update_etc_hosts_file }}"
  loop: "{{ update_etc_hosts_list }}"
  loop_control:
    label: "{{ thishost.node_name }}"
    loop_var: thishost
  ansible.builtin.include_tasks:
    file: update_host_{{ thishost.state | default('present') }}.yml
