---
# Variables specific on IBM VPC platforms
#
# TODO: make sure to first respect 'ha_cluster' native variables
#
sap_ha_cluster_fence_agent_packages:
  - fence-agents-ibm-vpc

# __sap_ha_cluster_repos:
#  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rpms"
#    name: High Availability

sap_ha_cluster_stonith_required:
  agent: "stonith:fence_ibm_vpc"
  options:
    apikey: "{{ sap_ha_cluster_ibmcloud_api_key }}"
    region: "{{ sap_ha_cluster_ibmcloud_region }}"
