---

- name: Configure - Display SAP note number 3119751 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).number }}
          (version {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).version }}): Linux Requirements for SAP Kernel 754 and for SAP Kernel 788 and higher"

# Note: This file is only included for RHEL 8, so no further when condition is required here.

- name: Identify all 'compat-sap-c++-NUM.so' files with NUM >= 10
  ansible.builtin.find:
    paths: '/opt/rh/SAP/lib64'
    patterns: "compat-sap-c++-1*"
  register: __sap_netweaver_preconfigure_register_find_compat_sap_cpp

# Note: The file compat-sap-c++-NUM.so with NUM >= 10 will be available if the role sap_general_preconfigure has been run before,
# which is a requirement.
- name: Fail if there is no file 'compat-sap-c++-NUM.so' file with NUM >= 10
  ansible.builtin.fail:
    msg: There is no file '/opt/rh/SAP/lib64/compat-sap-c++-NUM.so' file with NUM >= 10!
  when: __sap_netweaver_preconfigure_register_find_compat_sap_cpp.matched == 0

# Note: All following tasks depend on the previous task not having failed, so no further when condition is used below.
- name: Set fact for file names from find result
  ansible.builtin.set_fact:
    __sap_netweaver_preconfigure_fact_compat_sap_cpp_filenames: "{{ __sap_netweaver_preconfigure_fact_compat_sap_cpp_filenames | d([]) + [__sap_netweaver_preconfigure_item.path | basename] }}"
  loop: "{{ __sap_netweaver_preconfigure_register_find_compat_sap_cpp.files }}"
  loop_control:
    loop_var: __sap_netweaver_preconfigure_item
    label: "{{ __sap_netweaver_preconfigure_item.path }}"

- name: Set fact for the latest 'compat-sap-c++.NUM.so' file name
  ansible.builtin.set_fact:
    __sap_netweaver_preconfigure_fact_compat_sap_cpp_latest: "{{ __sap_netweaver_preconfigure_fact_compat_sap_cpp_filenames | sort | last }}"

- name: Display the identified 'compat-sap-c++-NUM.so' file name
  ansible.builtin.debug:
    msg: "File /opt/rh/SAP/lib64/{{ __sap_netweaver_preconfigure_fact_compat_sap_cpp_latest }} is present."

- name: Ensure there is a symlink in directory '/opt/rh/SAP/lib64' named 'libstdc++.so.6', pointing to '{{ __sap_netweaver_preconfigure_fact_compat_sap_cpp_latest }}'
  ansible.builtin.file:
    src: "{{ __sap_netweaver_preconfigure_fact_compat_sap_cpp_latest }}"
    dest: "/opt/rh/SAP/lib64/libstdc++.so.6"
    state: link

- name: Ensure directory '{{ sap_netweaver_preconfigure_rpath }}' is present
  ansible.builtin.file:
    path: "{{ sap_netweaver_preconfigure_rpath }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure there is a symlink in directory '{{ sap_netweaver_preconfigure_rpath }}' named 'libstdc++.so.6' pointing to '/opt/rh/SAP/lib64/libstdc++.so.6'
  ansible.builtin.file:
    src: /opt/rh/SAP/lib64/libstdc++.so.6
    dest: "{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6"
    state: link
