---

- name: Configure - Display SAP note number 3119751 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).number }}
          (version {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).version }}): Linux Requirements for SAP Kernel 754 and for SAP Kernel 788 and higher"

# Reason for noqa: We do not want to fail if there is no output from the ls command.
- name: Indentify the latest compat-sap-c++-NUM.so file with NUM >= 10 # noqa risky-shell-pipe
  ansible.builtin.shell:
  args:
    cmd: ls compat-sap-c++-1* | sort | tail -1
    chdir: /opt/rh/SAP/lib64
  register: __sap_netweaver_preconfigure_register_ls_compat_sap_cpp
  when: ansible_distribution_major_version == '8'
  changed_when: false

# Note: The file compat-sap-c++-NUM.so file with NUM >= 10 will be available if the role sap_general_preconfigure has been run before.
- name: Fail if there is no file compat-sap-c++-NUM.so file with NUM >= 10
  ansible.builtin.fail:
    msg: |
      - There is no file /opt/rh/SAP/lib64/compat-sap-c++-NUM.so file with NUM >= 10.
      - Make sure that package compat-sap-c++-10 or later is installed.
  when:
    - ansible_distribution_major_version == '8'
    - (__sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout is undefined or
       __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout is none or
       __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout | length == 0)

- name: Display the identified compat-sap-c++-NUM.so file name
  ansible.builtin.debug:
    msg: "File /opt/rh/SAP/lib64/{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }} is present."

- name: Ensure necessary symlinks for RHEL 8 are available
  when:
    - ansible_distribution_major_version == '8'
    - __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout | length > 0
  block:

    - name: Ensure there is a symlink in directory '/opt/rh/SAP/lib64' named 'libstdc++.so.6', pointing to '{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}'
      ansible.builtin.file:
        src: "{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}"
        dest: "/opt/rh/SAP/lib64/libstdc++.so.6"
        state: link

    - name: Ensure directory '{{ sap_netweaver_preconfigure_rpath }}' is present
      ansible.builtin.file:
        path: "{{ sap_netweaver_preconfigure_rpath }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure there is a symlink in directory '{{ sap_netweaver_preconfigure_rpath }}' named 'libstdc++.so.6' pointing to '/opt/rh/SAP/lib64/libstdc++.so.6'
      ansible.builtin.file:
        src: /opt/rh/SAP/lib64/libstdc++.so.6
        dest: "{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6"
        state: link
