---

- name: Configure - Display SAP note number 3119751 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).number }}
          (version {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '^3119751$') | first).version }}): Linux Requirements for SAP Kernel 754 and for SAP Kernel 788 and higher"

# Note: This file is only included for RHEL 8, so no further when condition is required here.

- name: Identify the latest compat-sap-c++-NUM.so file with NUM >= 10 # noqa risky-shell-pipe
  ansible.builtin.shell:
  args:
    cmd: ls compat-sap-c++-1* | sort | tail -1
    chdir: /opt/rh/SAP/lib64
  register: __sap_netweaver_preconfigure_register_ls_compat_sap_cpp
  changed_when: false

# Note: The file compat-sap-c++-NUM.so file with NUM >= 10 will be available if the role sap_general_preconfigure has been run before.
- name: Assert that there is at least one file /opt/rh/SAP/lib64/compat-sap-c++-NUM.so with NUM >= 10
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout | length > 0
    fail_msg: "FAIL: There is no file /opt/rh/SAP/lib64/compat-sap-c++-NUM.so file with NUM >= 10!"
    success_msg: "PASS: Found file /opt/rh/SAP/lib64/{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"

# Verify /opt/rh/SAP/lib64/libstdc++.so.6
- name: Get info about file /opt/rh/SAP/lib64/libstdc++.so.6
  ansible.builtin.stat:
    path: /opt/rh/SAP/lib64/libstdc++.so.6
  register: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert

- name: Assert that file /opt/rh/SAP/lib64/libstdc++.so.6 exists
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert.stat.exists
    fail_msg: "FAIL: File '/opt/rh/SAP/lib64/libstdc++.so.6' does not exist!"
    success_msg: "PASS: File '/opt/rh/SAP/lib64/libstdc++.so.6' exists."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"

- name: Assert that file '/opt/rh/SAP/lib64/libstdc++.so.6' is a symlink
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert.stat.islnk
    fail_msg: "FAIL: File '/opt/rh/SAP/lib64/libstdc++.so.6' is not a symlink!"
    success_msg: "PASS: File '/opt/rh/SAP/lib64/libstdc++.so.6' is a symlink."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert.stat.exists

- name: Assert that file '/opt/rh/SAP/lib64/libstdc++.so.6' is a symlink to '{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}'
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert.stat.lnk_target == __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout
    fail_msg: "FAIL: File '/opt/rh/SAP/lib64/libstdc++.so.6' is not a symlink to '{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}!'"
    success_msg: "PASS: File '/opt/rh/SAP/lib64/libstdc++.so.6' is a symlink to '{{ __sap_netweaver_preconfigure_register_ls_compat_sap_cpp.stdout }}'."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_netweaver_preconfigure_register_stat_opt_rh_libstdc_assert.stat.exists

- name: Get info about file '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6'
  ansible.builtin.stat:
    path: "{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6"
  register: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert

- name: Assert that file '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' exists
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert.stat.exists
    fail_msg: "FAIL: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' does not exist!"
    success_msg: "PASS: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' exists."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"

- name: Assert that file '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is a symlink
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert.stat.islnk
    fail_msg: "FAIL: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is not a symlink!"
    success_msg: "PASS: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is a symlink."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert.stat.exists

- name: Assert that file '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is a symlink to '/opt/rh/SAP/lib64/libstdc++.so.6'
  ansible.builtin.assert:
    that: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert.stat.lnk_target == '/opt/rh/SAP/lib64/libstdc++.so.6'
    fail_msg: "FAIL: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is not a symlink to '/opt/rh/SAP/lib64/libstdc++.so.6'!"
    success_msg: "PASS: File '{{ sap_netweaver_preconfigure_rpath }}/libstdc++.so.6' is a symlink to '/opt/rh/SAP/lib64/libstdc++.so.6'."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_netweaver_preconfigure_register_stat_usr_sap_libstdc_assert.stat.exists
