---
# The following tasks will check which SAP landscape can be configured with
# the provided parameters.
# It will validate if requirements are met for the cluster configuration.
- name: "{{ __tname }} Set landscape to scale-up if there are only 2 nodes"
  ansible.builtin.set_fact:
    sap_ha_cluster_sap_type: scaleup
  when:
    - ansible_play_hosts|length == 2
    - sap_ha_cluster_sap_type is not defined

# TODO: validate the value of sap_ha_cluster_sap_type to
# be a supported key
