---
# Platform detection for cloud platforms.
# Potentially also useful for other virtual or hardware platforms.

### AWS facts already available in Ansible
#
# ansible_bios_vendor: "Amazon EC2"
# ansible_bios_version: "1.0"
# ansible_board_asset_tag: "i-043d3c1a889ed9016"
# ansible_board_name: "NA"
# ansible_board_serial: "NA"
# ansible_board_vendor: "Amazon EC2"
# ansible_board_version: "NA"
# ansible_chassis_asset_tag: "Amazon EC2"
# ansible_chassis_serial: "NA"
# ansible_chassis_vendor: "Amazon EC2"
# ansible_chassis_version: "NA"
# ansible_product_name: "r5.8xlarge"
# ansible_system_vendor: "Amazon EC2"

# TODO: smarter detection based on multiple facts and providing one standard
# name for use as platform type in related include files

- name: "SAP HA Cluster - Set platform type based on Ansible facts"
  ansible.builtin.set_fact:
    __sap_ha_cluster_vm_asset_tag: "{{ ansible_facts.node.ansible_chassis_asset_tag | default('NA') }}"
    # __sap_ha_cluster_platform_type:
