---
# Platform detection for cloud platforms.
# Potentially also useful for other virtual or hardware platforms.

- name: "{{ __tname }} Set platform type based on Ansible facts"
  ansible.builtin.set_fact:
    __sap_ha_cluster_vm_asset_tag: "{{ ansible_facts.node.ansible_chassis_asset_tag | default('NA') }}"
