---
# Platform detection for cloud platforms.
# Potentially also useful for other virtual or hardware platforms.

# Possible useful ansible facts are:
# - ansible_chassis_asset_tag
# - ansible_board_asset_tag
# - ansible_system_vendor

# TODO: smarter detection based on multiple facts and providing one standard
# name for use as platform type in related include files

- name: "{{ __tname }} Set platform type based on Ansible facts"
  ansible.builtin.set_fact:
    __sap_ha_cluster_vm_asset_tag: "{{ ansible_facts.node.ansible_chassis_asset_tag | default('NA') }}"
    # __sap_ha_cluster_platform_type:
