---
# Platform detection for cloud and other infrastructure platforms.

### AWS facts already available in Ansible
#
# ansible_bios_vendor: "Amazon EC2"
# ansible_bios_version: "1.0"
# ansible_board_asset_tag: "i-043d3c1a889ed9016"
# ansible_board_name: "NA"
# ansible_board_serial: "NA"
# ansible_board_vendor: "Amazon EC2"
# ansible_board_version: "NA"
# ansible_chassis_asset_tag: "Amazon EC2"
# ansible_chassis_serial: "NA"
# ansible_chassis_vendor: "Amazon EC2"
# ansible_chassis_version: "NA"
# ansible_product_name: "r5.8xlarge"
# ansible_system_vendor: "Amazon EC2"

# TODO: detection based on multiple facts and providing one standard
# name for use as platform type in related include files

- name: "SAP HA Cluster - Check if platform is AWS EC2 VM"
  when:
    - ansible_system_vendor == 'Amazon EC2'
  ansible.builtin.set_fact:
    __sap_ha_cluster_platform: vm_aws_ec2


# TODO: workaround, pcmk_host_map must be defined before stonith vars are built
# Mapping will probably be different on non-AWS platforms. To be adjusted...
- name: "SAP HA Cluster - Construct pcmk_host_map for stonith on AWS EC2 VM"
  when: __sap_ha_cluster_platform == 'vm_aws_ec2'
  ansible.builtin.set_fact:
    __sap_ha_cluster_pcmk_host_map: >-
      {% for entry in sap_hana_cluster_nodes -%}
        {% for host in ansible_play_hosts -%}
          {% if hostvars[host].ansible_hostname == entry.node_name -%}
            {{ entry.node_name }}:{{ hostvars[host].ansible_board_asset_tag }}
      {%- if not loop.last %};{% endif %}{%- endif %}{%- endfor %}{%- endfor %}

- name: "SAP HA Cluster - Include platform specific variables"
  ansible.builtin.import_tasks: platform/include_vars_platform.yml
