---
# The following tasks will check which SAP landscape can be configured with
# the provided parameters.
# It will validate if requirements are met for the cluster configuration.

# TODO: fail if there is only one host in the play?
# TODO: check play hosts against cluster nodes definition - there should be no
#       hosts in the play that are undefined?

# 2 nodes are also valid for other scenarios.
# TODO: collect possible rules for target landscapes

- name: "SAP HA Cluster - Set landscape to scale-up if there are only 2 nodes"
  when:
    - ansible_play_hosts|length == 2
    - sap_ha_cluster_sap_type is not defined
  ansible.builtin.set_fact:
    sap_ha_cluster_sap_type: scaleup

# TODO: validate the value of sap_ha_cluster_sap_type to
# be a supported key (to catch mismatches if it is user-defined)
