---
# Reminder: This file is included in a loop over a dictionary.

- name: "SAP HA Cluster - Add resource: VIP for {{ vip_list_item.key }}"
  when:
    - sap_ha_cluster_vip_resource_name ~ '_' ~ vip_list_item.key not in (__sap_ha_cluster_resource_primitives | map(attribute='id'))
  ansible.builtin.set_fact:
    __sap_ha_cluster_resource_primitives: "{{ __sap_ha_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "{{ sap_ha_cluster_vip_resource_name }}_{{ vip_list_item.key }}"
      agent: "ocf:heartbeat:IPaddr2"
      instance_attrs:
        - attrs:
            - name: ip
              value: "{{ vip_list_item.value }}"

- name: "SAP HA Cluster - Add resource: Private IP for {{ vip_list_item.key }}"
  when:
    - ('pri' ~ sap_ha_cluster_vip_resource_name ~ '_' ~ vip_list_item.key) not in (__sap_ha_cluster_resource_primitives | map(attribute='id'))
  ansible.builtin.set_fact:
    __sap_ha_cluster_resource_primitives: "{{ __sap_ha_cluster_resource_primitives + [__resource_vip] }}"
  vars:
    __resource_vip:
      id: "pri{{ sap_ha_cluster_vip_resource_name }}_{{ vip_list_item.key }}"
      agent: "ocf:heartbeat:awsvip"
      instance_attrs:
        - attrs:
            - name: secondary_private_ip
              value: "{{ vip_list_item.value }}"

- name: "SAP HA Cluster - Add resource group: {{ sap_ha_cluster_vip_resource_group_name }}"
  when:
    - __vip_group.id is not in (__sap_ha_cluster_resource_groups | map(attribute='id'))
  ansible.builtin.set_fact:
    __sap_ha_cluster_resource_groups: "{{ __sap_ha_cluster_resource_groups + [__vip_group] }}"
  vars:
    __vip_group:
      id: "{{ sap_ha_cluster_vip_resource_group_name }}_{{ vip_list_item.key }}"
      resource_ids:
        - "{{ sap_ha_cluster_vip_resource_name }}_{{ vip_list_item.key }}"
        - "pri{{ sap_ha_cluster_vip_resource_name }}_{{ vip_list_item.key }}"

# Start the VIP(s) only after the HANA resource has been promoted
- name: "SAP HA Cluster - Add order constraint: Primary VIP starts after DB is promoted"
  when:
    - __constraint_order_vip.resource_then not in (__sap_ha_cluster_constraints_order | map(attribute='resource_then'))
    - vip_list_item.key in __sap_ha_cluster_primary_synonyms
  ansible.builtin.set_fact:
    __sap_ha_cluster_constraints_order: "{{ __sap_ha_cluster_constraints_order + [__constraint_order_vip] }}"
  vars:
    __constraint_order_vip:
      resource_first:
        id: "{{ sap_ha_cluster_hana_resource_clone_name }}"
        action: promote
      resource_then:
        id: "{{ sap_ha_cluster_vip_resource_group_name }}_{{ vip_list_item.key }}"
        action: start

# The VIP only runs where HANA is promoted
- name: "SAP HA Cluster - Add colocation constraint: Primary VIP runs where HANA is promoted"
  when:
    - __constraint_colo_vip.resource_follower not in (__sap_ha_cluster_constraints_colocation | map(attribute='resource_follower'))
    - vip_list_item.key in __sap_ha_cluster_primary_synonyms
  ansible.builtin.set_fact:
    __sap_ha_cluster_constraints_colocation: "{{ __sap_ha_cluster_constraints_colocation + [__constraint_colo_vip] }}"
  vars:
    __constraint_colo_vip:
      resource_leader:
        id: "{{ sap_ha_cluster_hana_resource_clone_name }}"
        role: promoted
      resource_follower:
        id: "{{ sap_ha_cluster_vip_resource_group_name }}_{{ vip_list_item.key }}"
      options:
        - name: score
          value: 2000
