---
# Create or combine input parameters for the ha_cluster role.

- name: "SAP HA Cluster - Set cluster name"
  ansible.builtin.set_fact:
    __sap_ha_cluster_cluster_name: "{{ ha_cluster_cluster_name | default(sap_ha_cluster_cluster_name) }}"

- name: "SAP HA Cluster - Register the 'hacluster' user password"
  ansible.builtin.set_fact:
    __sap_ha_cluster_hacluster_password: "{{ ha_cluster_hacluster_password | default(sap_ha_cluster_hacluster_password) }}"
  no_log: true

- name: "SAP HA Cluster - Combine defined extra packages"
  ansible.builtin.set_fact:
    __sap_ha_cluster_extra_packages: "{{ __sap_ha_cluster_extra_packages + sap_ha_cluster_extra_packages }}"
  when:
    - sap_ha_cluster_extra_packages is defined
