---
# Variables containing variables must be constructed with values
# to be fed into an included role

- name: "{{ __tname }} Set cluster name"
  ansible.builtin.set_fact:
    __sap_ha_cluster_cluster_name: "{{ ha_cluster_cluster_name | default(sap_ha_cluster_cluster_name) }}"

- name: "{{ __tname }} Register the 'hacluster' user password"
  ansible.builtin.set_fact:
    __sap_ha_cluster_hacluster_password: "{{ ha_cluster_hacluster_password | default(sap_ha_cluster_hacluster_password) }}"
  no_log: true

- name: "{{ __tname }} Combine defined extra packages"
  ansible.builtin.set_fact:
    __sap_ha_cluster_extra_packages: "{{ __sap_ha_cluster_extra_packages + sap_ha_cluster_extra_packages }}"
  when:
    - sap_ha_cluster_extra_packages is defined
