---
# The following variables are constructed here in order to be provided as
# input for the included 'ha_cluster' system role.

- name: "SAP HA Cluster - Define cluster properties"
  when:
    - item.name not in
      (__sap_ha_cluster_cluster_properties | map(attribute='attr') | flatten | map(attribute='name'))
  ansible.builtin.set_fact:
    __sap_ha_cluster_cluster_properties: "{{ __sap_ha_cluster_cluster_properties + [{'attr': item}] }}"
  loop_control:
    label: "{{ item.name }}"
  loop:
    - name: stonith-enabled
      value: true
    - name: stonith-timeout
      value: 900
    - name: concurrent-fencing
      value: true

# The STONITH resource is an element in the cluster_resource_primitives list
- name: "SAP HA Cluster - Construct stonith resources definition"
  when:
    - sap_ha_cluster_stonith_resources is defined
    - sap_ha_cluster_stonith_resources is iterable
  ansible.builtin.set_fact:
    __sap_ha_cluster_resource_primitives: "{{ __sap_ha_cluster_resource_primitives + sap_ha_cluster_stonith_resources }}"
  #no_log: true  # stonith resources usually contain secrets
