---
# The following variables are constructed here in order to be provided as
# input for the included 'ha_cluster' system role.
#
# TODO: make sure to first respect 'ha_cluster' native variables

- name: "{{ __tname }} Construct stonith resources definition "
  ansible.builtin.set_fact:
    # STONITH resource definition
    # This will be added to the cluster resources list

# workaround / placeholder until modular fencing resource logic
# has been invented
    sap_ha_cluster_stonith_resource_primitives: "{{ sap_ha_cluster_stonith_resources }}"  # from groupvars
  no_log: true
