---
# The VIP resource construction files are included in a loop to allow
# for multiple IPs to be configured in cluster resources

- name: "SAP HA Cluster - Include variable construction for VIP resources"
  when:
    - __sap_ha_cluster_cloud_platform | length == '0'
    - (vip_list_item.value is defined) and (vip_list_item.value != '')
  ansible.builtin.include_tasks: construct_vars_vip_resources_default.yml
  loop: "{{ query('dict', sap_ha_cluster_vip_address) }}"
  loop_control:
    index_var: loop_index
    loop_var: vip_list_item

- name: "SAP HA Cluster - Include variable construction for VIP resources on AWS"
  when:
    - __sap_ha_cluster_cloud_platform == 'aws'
    - (vip_list_item.value is defined) and (vip_list_item.value != '')
  ansible.builtin.include_tasks: construct_vars_vip_resources_aws.yml
  loop: "{{ query('dict', sap_ha_cluster_vip_address) }}"
  loop_control:
    index_var: loop_index
    loop_var: vip_list_item
