---
# The VIP resource construction files are included in a loop to allow
# for multiple IPs to be configured in cluster resources

- name: "SAP HA Cluster - Include variable construction for VIP resources"
  when:
    - __sap_ha_cluster_platform not in ['aws_ec2_instance', 'ibmcloud']
    - (vip_list_item.value is defined) and (vip_list_item.value != '')
  ansible.builtin.include_tasks: construct_vars_vip_resources_default.yml
  loop: "{{ query('dict', sap_ha_cluster_vip_address) }}"
  loop_control:
    index_var: loop_index
    loop_var: vip_list_item

- name: "SAP HA Cluster - Include variable construction for VIP resources on platforms"
  when:
    - __sap_ha_cluster_cloud_platform != ''
    - (vip_list_item.value is defined) and (vip_list_item.value != '')
  ansible.builtin.include_tasks: "platform/construct_vars_vip_resources_{{ __sap_ha_cluster_platform }}.yml"
  loop: "{{ query('dict', sap_ha_cluster_vip_address) }}"
  loop_control:
    index_var: loop_index
    loop_var: vip_list_item
