---

- name: SAP HANA hdblcm prepare - Create temp dir - {{ sap_hana_install_software_directory }}/tmp
  file:
    path: "{{ sap_hana_install_software_directory }}/tmp"
    state: directory
    mode: 0755

- name: SAP HANA hdblcm prepare - Extracting {{ passed_sap_hana_install_components_sar }}
  command: >-
    {{ sap_hana_install_software_directory }}/{{ __sap_hana_install_fact_sapcar_file_name }} \
    -R {{ sap_hana_install_software_directory }}/tmp
    -xvf {{ sap_hana_install_software_directory }}/{{ passed_sap_hana_install_components_sar }} \
    -manifest SIGNATURE.SMF
  register: __sap_hana_install_register_extract
  args:
    chdir: "{{ sap_hana_install_software_directory }}"
  changed_when: "'SAPCAR: processing archive' in __sap_hana_install_register_extract.stdout"

- name: SAP HANA hdblcm prepare - Create directory if SAP Host Agent
  file:
    path: "{{ sap_hana_install_software_directory }}/tmp/SAP_HOST_AGENT"
    state: directory
    mode: 0755
    owner: root
    group: root
  when: "'SAPHOST' in passed_sap_hana_install_components_sar"

- name: SAP HANA hdblcm prepare - Prepare extracted dir
  shell: |
    extracted_dir=$(ls -d */)
    cp SIGNATURE.SMF $extracted_dir
    cp -R $extracted_dir ../extracted/$extracted_dir
  args:
    chdir: "{{ sap_hana_install_software_directory }}/tmp"
  changed_when: no

- name: SAP HANA hdblcm prepare - Remove temp dir - {{ sap_hana_install_software_directory }}/tmp
  file:
    path: "{{ sap_hana_install_software_directory }}/tmp"
    state: absent
