# [A] Create and Store Connection Info in hdbuserstore for SYSTEMDB
- name: SAP HSR - [A] Create and Store Connection Info in hdbuserstore
  shell: |
        /usr/sap/{{ sap_ha_install_hana_hsr_sid}}/SYS/exe/hdb/hdbuserstore \
        SET {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} {{ ansible_hostname }}:3{{ sap_ha_install_hana_hsr_instance_number }}13 SYSTEM '{{ sap_ha_install_hana_hsr_db_system_password }}'
  args:
     executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
