# [A] Set parameter log_mode
- name: SAP HSR - [A] Set log_mode to normal
  shell: |
        /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/exe/hdb/hdbsql \
        -U {{ sap_ha_install_hana_hsr_hdbuserstore_system_backup_user }} \
        -m <<EOF
        ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'normal' WITH RECONFIGURE;
        ALTER SYSTEM ALTER CONFIGURATION('global.ini','HOST','{{ ansible_hostname }}') SET ('persistence','log_mode') = 'normal' WITH RECONFIGURE;
        EOF
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"

