---

# Commented out for now
# Will let the handler / external role update /etc/hosts
# - name: SAP HSR - Update /etc/hosts
#   include_tasks: update_etchosts.yml

- name: SAP HSR - Configure Firewall
  include_tasks: configure_firewall.yml

- name: SAP HSR - hdbuserstore
  include_tasks: hdbuserstore.yml

- name: SAP HSR - Log Mode
  include_tasks: log_mode.yml

- name: SAP HSR - PKI Files
  include_tasks: pki_files.yml

- name: SAP HSR - Run Backup
  include_tasks: run_backup.yml

- name: SAP HSR - Configure HSR
  include_tasks: configure_hsr.yml