# [1] Copy the system PKI files to /tmp

- name: Copy the system PKI files to /tmp
  tags: hsr_pki
  fetch:
    src: "{{ item }}"
    dest: /tmp/
    flat: true
  loop:
    - /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/SSFS_{{ sap_ha_install_hana_hsr_sid }}.DAT
    - /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/key/SSFS_{{ sap_ha_install_hana_hsr_sid }}.KEY
  when:
    - sap_ha_install_hana_hsr_role == 'primary'

# Cant copy or fetch files between 2 nodes because were using
# --connection: local
# Moving files step is temporarily set in TF
# - name: SAP HSR [A] - Check if PKI files are copied
#  tags: hsr_pki
#  command: sum /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/SSFS_{{ sap_ha_install_hana_hsr_sid }}.DAT
#  register: sap_ha_install_hana_hsr_pki_sum
#  when: 
#    - sap_ha_install_hana_hsr_role == 'primary'
# - name: SAP HSR [A] - Check if PKI files are copied
#  tags: hsr_pki
#  command: sum /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/SSFS_{{ sap_ha_install_hana_hsr_sid }}.DAT
#  register: sap_ha_install_hana_hsr_pki_sum2
#  when:
#
#    - sap_ha_install_hana_hsr_role=='primary'
- name: SAP HSR - print PKI sum2 
  tags: hsr_pki
  debug:
#    msg: {{ sap_ha_install_hana_hsr_pki_sum2.stdout.split() }}
    msg: Bla Blub
  when: 
    - sap_ha_install_hana_hsr_role=='secondary'

# - name: "SAP HSR - check local file on controller"
#   tags: hsr_pki
#   hosts: localhost
#   stat:
#     path: /tmp
#   register: local_tmp

# - name: "SAP HSR - print local file"
#   tags: hsr_pki
#   debug: 
#     msg: "Local File Exists"
#   when: local_tmp.exists

# [2] Copy the system PKI files from /tmp to /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/
- name: Copy the system PKI files from /tmp to /usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/
  tags: hsr_pki
  copy:
    src: "/tmp/{{ item.file }}"
    dest: "{{ item.path }}{{ item.file }}"
    owner: "{{ sap_ha_install_hana_hsr_sid | lower }}adm"
    group: sapsys
    mode: '{{ item.mode }}'
  loop:
    - { path: '/usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/data/', file: 'SSFS_{{ sap_ha_install_hana_hsr_sid }}.DAT', mode: '0600' }
    - { path: '/usr/sap/{{ sap_ha_install_hana_hsr_sid }}/SYS/global/security/rsecssfs/key/', file: 'SSFS_{{ sap_ha_install_hana_hsr_sid }}.KEY', mode: '0640' }
  when:
    - sap_ha_install_hana_hsr_role == 'secondary'