---
- name: "SAP HSR - Add Cluster Nodes to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    create: false
    state: present
    backup: yes
    line: "{{ item.ip }}\t{{ item.name }}.{{ sap_ha_install_hana_hsr_fqdn }}\t{{ item.name }}"
    regexp: (?i)^\s*{{ item.ip }}\s+{{ item.name }}
  loop: "{{ cluster_nodes }}"
  loop_control:
    label: "{{ item.ip }} {{ item.name }}.{{ sap_ha_install_hana_hsr_fqdn }} {{ item.name }}"
