# Product ID for New Installation
sap_swpm_product_catalog_id: NW_ERS:S4HANA2020.CORE.HDB.ABAPHA

# Software
sap_swpm_software_path: /software/download_basket
sap_swpm_sapcar_path: /software/download_basket
sap_swpm_swpm_path: /software/download_basket

# NW Passwords
sap_swpm_master_password: "NewPass$321"
sap_swpm_ddic_000_password: "NewPass$321"

# NW Instance Parameters
sap_swpm_sid: S4D
sap_swpm_ers_instance_nr: "02"
sap_swpm_ers_instance_hostname: "s4h2020b"
sap_swpm_fqdn: "poc.cloud"
sap_swpm_virtual_hostname: ""

# Unix User ID
sap_swpm_sapadm_uid: '3000'
sap_swpm_sapsys_gid: '3001'
sap_swpm_sidadm_uid: '3001'
