---

# Product ID for New Installation
sap_swpm_product_catalog_id: NW_Webdispatcher:NW750.IND.PD

# Software
sap_swpm_software_path: /software
sap_swpm_sapcar_path: /software
sap_swpm_swpm_path: /software

# NW Passwords
sap_swpm_master_password: "NewPass$321"

# NW Instance Parameters
sap_swpm_sid: WD1
sap_swpm_wd_instance_nr: '03'

# Backend Connection
sap_swpm_wd_system_connectivity: 'false'
sap_swpm_wd_activate_icf: 'false'
sap_swpm_wd_backend_sid: 'S4H'
sap_swpm_wd_backend_ms_http_port: '8001'
sap_swpm_wd_backend_ms_host: "{{ ansible_hostname }}"
sap_swpm_wd_backend_rfc_host: "{{ ansible_hostname }}"
sap_swpm_wd_backend_rfc_instance_nr: "01"
sap_swpm_wd_backend_rfc_ddic_000_password: "NewPass$321"
sap_swpm_wd_backend_scenario_size: '500'
sap_swpm_wd_virtual_host: "{{ ansible_hostname }}"

# SAP Host Agent
sap_swpm_install_saphostagent: 'false'
