---

- name: Install the package which provides the semanage command
  ansible.builtin.package:
    state: latest
    name: policycoreutils-python-utils

- name: Check if the directory '/hana' exists
  ansible.builtin.stat:
    path: '/hana'
  register: __sap_hana_preconfigure_register_stat_hana
  failed_when: false

- name: Report that SELinux checking will not be performed in case the directory '/hana' does not exist
  ansible.builtin.debug:
    msg: "INFO: SELinux checks will not be run because the directory '/hana' does not exist."
  when: not __sap_hana_preconfigure_register_stat_hana.stat.exists or
        (__sap_hana_preconfigure_register_stat_hana.stat.isdir is defined and
           not __sap_hana_preconfigure_register_stat_hana.stat.isdir)

- name: Count SELinux configuration database entries for '/hana'
  ansible.builtin.shell: set -o pipefail && semanage fcontext -l | awk 'BEGIN{a=0}$1=="/hana(/.*)?"&&$NF~/usr_t/{a++}END{print a}'
  register: __sap_hana_preconfigure_register_semanage_fcontext_hana_result
  when: __sap_hana_preconfigure_register_stat_hana.stat.isdir is defined and __sap_hana_preconfigure_register_stat_hana.stat.isdir

- name: Assert that there is an entry for '/hana' in the SELinux configuration database
  ansible.builtin.assert:
    that:
      __sap_hana_preconfigure_register_semanage_fcontext_hana_result.stdout | int != 0
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_hana_preconfigure_register_stat_hana.stat.isdir is defined and __sap_hana_preconfigure_register_stat_hana.stat.isdir

- name: Count files in '/hana' and below without SELinux `usr_t` file context
  ansible.builtin.shell: set -o pipefail && find /hana -exec ls -ldZ {} \; | awk 'BEGIN{a=0}$5!~/usr_t/{a++}END{print a}'
  register: __sap_hana_preconfigure_register_ls_fcontext_hana_result
  when: __sap_hana_preconfigure_register_stat_hana.stat.isdir is defined and __sap_hana_preconfigure_register_stat_hana.stat.isdir

- name: Assert that all files in '/hana' and below have the usr_t file context
  ansible.builtin.assert:
    that:
      __sap_hana_preconfigure_register_selinux_fcontext_hana_result.stdout | int == 0
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
  when: __sap_hana_preconfigure_register_stat_hana.stat.isdir is defined and __sap_hana_preconfigure_register_stat_hana.stat.isdir
