---

- name: Configure '/hana' SELinux file labels
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.selinux
  vars:
    selinux_booleans:
      - { name: 'selinuxuser_execmod', state: 'on' }
    selinux_fcontexts:
      - { target: '/hana(/.*)?', setype: 'usr_t' }
    selinux_restore_dirs:
      - '/hana'
  when: sap_hana_preconfigure_modify_selinux_labels
