---

- name: Configure - Display SAP note number 2002167 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2002167$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2002167$') | first).version }}): Configure RHEL 7"
  tags:
    - sap_general_preconfigure_configuration
    - sap_general_preconfigure_configuration_all_steps

- name: Import tasks from '2002167/02-configuration-changes.yml'
  ansible.builtin.import_tasks: 2002167/02-configuration-changes.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2002167_02 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2002167_02
    - sap_general_preconfigure_firewall
    - sap_general_preconfigure_selinux

- name: Import tasks from '2002167/03-setting-the-hostname.yml'
  ansible.builtin.import_tasks: 2002167/03-setting-the-hostname.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2002167_03 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2002167_03
    - sap_general_preconfigure_hostname
    - sap_general_preconfigure_etc_hosts
    - sap_general_preconfigure_dns-name-resolution

- name: Import tasks from '2002167/04-linux-kernel-parameters.yml'
  ansible.builtin.import_tasks: 2002167/04-linux-kernel-parameters.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2002167_04 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2002167_04
    - sap_general_preconfigure_kernel_parameters

- name: Import tasks from '2002167/05-process-resource-limits.yml'
  ansible.builtin.import_tasks: 2002167/05-process-resource-limits.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2002167_05 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2002167_05
    - sap_general_preconfigure_nproc_limits

- name: Import tasks from '2002167/06-additional-notes-for-installing-sap-systems.yml'
  ansible.builtin.import_tasks: 2002167/06-additional-notes-for-installing-sap-systems.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2002167_06 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2002167_06
    - sap_general_preconfigure_libldap
    - sap_general_preconfigure_liblber
    - sap_general_preconfigure_systemd_tmpfiles
