---

- name: Configure - Display SAP note number 2772999 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2772999$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2772999$') | first).version }}): Configure RHEL 8"
  tags:
    - sap_general_preconfigure_configuration
    - sap_general_preconfigure_configuration_all_steps

- name: Import tasks from '2772999/02-configure-selinux.yml'
  ansible.builtin.import_tasks: 2772999/02-configure-selinux.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_02 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_02
    - sap_general_preconfigure_selinux

- name: Import tasks from '2772999/03-configure-hostname.yml'
  ansible.builtin.import_tasks: 2772999/03-configure-hostname.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_03 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_03
    - sap_general_preconfigure_hostname
    - sap_general_preconfigure_etc_hosts
    - sap_general_preconfigure_dns-name-resolution

- name: Import tasks from '2772999/04-configure-network-time-and-date.yml'
  ansible.builtin.import_tasks: 2772999/04-configure-network-time-and-date.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_04 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_04
    - sap_general_preconfigure_network_time_and_date

- name: Import tasks from '2772999/05-configure-firewall.yml'
  ansible.builtin.import_tasks: 2772999/05-configure-firewall.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_05 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_05
    - sap_general_preconfigure_firewall

- name: Import tasks from '2772999/06-configure-uuidd.yml'
  ansible.builtin.import_tasks: 2772999/06-configure-uuidd.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_06 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_06
    - sap_general_preconfigure_configure_uuidd

- name: Import tasks from '2772999/07-configure-tmpfs.yml'
  ansible.builtin.import_tasks: 2772999/07-configure-tmpfs.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_07 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_07
    - sap_general_preconfigure_configure_tmpfs

- name: Import tasks from '2772999/08-configure-linux-kernel-parameters.yml'
  ansible.builtin.import_tasks: 2772999/08-configure-linux-kernel-parameters.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_08 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_08
    - sap_general_preconfigure_kernel_parameters

- name: Import tasks from '2772999/09-configure-process-resource-limits.yml'
  ansible.builtin.import_tasks: 2772999/09-configure-process-resource-limits.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_09 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_09
    - sap_general_preconfigure_nproc_limits

- name: Import tasks from '2772999/10-configure-systemd-tmpfiles.yml'
  ansible.builtin.import_tasks: 2772999/10-configure-systemd-tmpfiles.yml
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_2772999_10 | d(false)
  tags:
    - sap_general_preconfigure_configuration_all_steps
    - sap_general_preconfigure_2772999_10
    - sap_general_preconfigure_systemd_tmpfiles
