- name: Set TSX
  lineinfile:
    path: /etc/default/grub
    backup: yes
    backrefs: yes
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
     - "tsx={{ sap_hana_rhv_guest_tsx }}"
  notify: "Regenerate grub2 conf handler"
  tags: grubconfig

