---

- name: Configure - List required SAP Notes
  ansible.builtin.debug:
    var: __sap_general_preconfigure_sapnotes_versions | difference([''])

- name: Configure - Set sap_hostname if not defined
  ansible.builtin.set_fact:
    sap_hostname: "{{ ansible_hostname }}"
  when: sap_hostname is not defined

- name: Configure - Set sap_domain if not defined
  ansible.builtin.set_fact:
    sap_domain: "{{ ansible_domain }}"
  when: sap_domain is not defined

- name: Configure - Set sap_ip if not defined
  ansible.builtin.set_fact:
    sap_ip: "{{ ansible_default_ipv4.address }}"
  when: sap_ip is not defined

- name: Configure - Set directory variables for setting SELinux file contexts
  ansible.builtin.set_fact:
    sap_general_preconfigure_fact_targets_setypes: "{{ sap_general_preconfigure_fact_targets_setypes | d([]) +
      [__sap_general_preconfigure_tmp_dict_target_setype] }}"
  loop: "{{ sap_general_preconfigure_sap_directories }}"
  loop_control:
    loop_var: line_item
  vars:
    __sap_general_preconfigure_tmp_dict_target_setype:
      target: "{{ line_item }}(/.*)?"
      setype: 'usr_t'
  when: sap_general_preconfigure_modify_selinux_labels

- name: Configure - Display directory variable
  ansible.builtin.debug:
    var: sap_general_preconfigure_fact_targets_setypes
  when: sap_general_preconfigure_modify_selinux_labels

- name: Configure - Create directories
  ansible.builtin.file:
    path: "{{ line_item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop: "{{ sap_general_preconfigure_sap_directories }}"
  loop_control:
    loop_var: line_item
  when: sap_general_preconfigure_create_directories or sap_general_preconfigure_modify_selinux_labels

- name: Configure - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/{{ sap_note_line_item.number }}.yml"
  with_items: "{{ __sap_general_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
