---
- name: "SAP Pacemaker Hana - Sudoer Configuration"
  include_tasks: 
    file: cluster_sudoer.yml
    apply:
      tags: 
        - pacemaker
        - srhook_sudo
  tags:
    - pacemaker
    - srhook_sudo

- name: "SAP Pacemaker Hana - Resource Configuration"
  include_tasks: 
    file: cluster_resources.yml
    apply:
      tags: 
        - pacemaker
        - ha_resources
  when:
    - sap_ha_set_hana_role == 'primary'
  tags:
    - pacemaker
    - ha_resources

- name: "SAP Pacemaker Hana - srhooks Configuration"
  include_tasks: 
    file: cluster_srhook.yml
    apply:
      tags: 
        - srhook
        - pacemaker
  tags:
    - srhook
    - pacemaker

- name: "SAP Pacemaker Hana - Constraints Configuration"
  include_tasks: 
    file: cluster_constraint.yml
    apply:
      tags:
        - ha_constraints
        - pacemaker
  when:
    - sap_ha_set_hana_role == 'primary'
  tags:
    - ha_constraints
    - pacemaker
