- name: SAP HANA HA - Disable Firewall
  include_tasks: disable_firewall.yml

# Part 1
- name: SAP HANA HA - SAPHanaSR python hook
  include_tasks: saphanasr_python_hook.yml
  when:
    - sap_ha_set_hana_part == '1'

# Part 2
- name: SAP HANA HA - Cluster Resources
  include_tasks: cluster_resources.yml
  when:
    - sap_ha_set_hana_part == '2'
