---

- name: Get unrar binary for extraction
  ansible.builtin.shell: curl https://www.rarlab.com/rar/rarlinux-x64-612.tar.gz | tar -xvz --strip-components=1 rar/unrar
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
