---

- name: SAP Install Media Detect - Prepare - Download rar tar file
  ansible.builtin.get_url:
    url: "{{ sap_install_media_detect_rar_url }}"
    dest: "{{ sap_install_media_detect_directory }}"
    mode: '0644'

- name: SAP Install Media Detect - Prepare - Extract unrar
  ansible.builtin.unarchive:
    src: "{{ sap_install_media_detect_directory }}/{{ sap_install_media_detect_rar_url.split('/')[-1:] | join() }}"
    dest: "{{ sap_install_media_detect_directory }}"
    remote_src: true
    include:
      - rar/unrar
    extra_opts:
      - --strip-components
      - 1

- name: SAP Install Media Detect - Prepare - Remove rar tar file
  ansible.builtin.file:
    path: "{{ sap_install_media_detect_directory }}/{{ sap_install_media_detect_rar_url.split('/')[-1:] | join() }}"
    state: absent

- name: SAP Install Media Detect - Prepare - set facts for unrar path
  ansible.builtin.set_fact:
    sap_install_media_detect_unrar_binary: "{{ sap_install_media_detect_directory }}/unrar"
