---
- name: Install libhugetlbfs
  yum:
    name: libhugetlbfs, libhugetlbfs-utils
    state: present

#XXX better location than rc.local?
- name: Add hugepage allocation to /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    marker: ""
    block: |
        hugeadm --create-mounts --pool-pages-min 1G:$(free -g | grep "Mem:" | awk '{print $2-"{{ sap_hana_rhv_hypervisor_reserved_ram }}"}')

- name: Set default hugepage size
  lineinfile:
    path: /etc/default/grub
    backup: yes
    backrefs: yes
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ item }}).*). *$'
    line: "\\1 {{ item }}\""
  with_items:
     - default_hugepagesz=1GB
     - hugepagesz=1GB
  notify: "Regenerate grub2 conf handler"
  tags: grubconfig
...
