- name: Gather package facts
  package_facts:


- name: Assert that all required packages are installed
  assert:
    that: "'{{ line_item }}' in ansible_facts.packages"
    fail_msg: "FAIL: Package '{{ line_item }}' is not installed!"
    success_msg: "PASS: Package '{{ line_item }}' is installed."
  with_items:
    - "{{ sap_hana_rhv_hypervisor_packages }}"
  loop_control:
    loop_var: line_item
  ignore_errors: "{{ sap_hana_rhv_hypervisor_ignore_failed_assertion }}"
