---
- name: Check file permissions
  command: "stat -c%a /usr/libexec/vdsm/hooks/before_vm_start/{{ item }}"
  register: __sap_hana_rhv_hypervisor_register_file_permissions_assert

- name: Assert hook file permissions
  assert:
    that: "__sap_hana_rhv_hypervisor_register_file_permissions_assert.stdout == '755'"
    fail_msg: "FAIL: Hook {{ item }} does not have the correct file permissions (!= 755)."
    success_msg: "PASS: Hook {{ item }} does have the correct file permissions (755)."
  ignore_errors: "{{ sap_hana_rhv_hypervisor_ignore_failed_assertion }}"

- name: Create tmp dir
  file:
    path: /tmp/sap_hana_rhv_hypervisor
    state: directory

- name: Copy hook for checking
  copy:
    dest: "/tmp/sap_hana_rhv_hypervisor/{{ item }}"
    src: "{{ item }}"

- name: Diff hook
  command: "diff -uw /tmp/sap_hana_rhv_hypervisor/{{ item }} /usr/libexec/vdsm/hooks/before_vm_start/{{ item }}"
  register: __sap_hana_rhv_hypervisor_register_hook_diff_assert
  ignore_errors: yes

- name: Assert hook content
  assert:
    that: "__sap_hana_rhv_hypervisor_register_hook_diff_assert.rc == 0"
    fail_msg: "FAIL: Hook {{ item }} has been modified, please investigate manually."
    success_msg: "PASS: Hook {{ item }} not modified"
  ignore_errors: "{{ sap_hana_rhv_hypervisor_ignore_failed_assertion }}"
...
