---

# Important variables

sap_storage_cloud_type: 'generic'
# generic | az | aws

sap_storage_sap_type: 'sap_onehost'
# sap_onehost | sap_hana | sap_nw

#sap_storage_action:
# prepare | remove

sap_storage_setup_nfs_options: 'hard,acl'
sap_storage_setup_nfs_filesystem: nfs4


# Azure variables

sap_storage_az_imds_json:
sap_storage_az_imds_url: 'http://169.254.169.254/metadata/instance/compute?api-version=2020-09-01'
sap_storage_az_vmsize_url: 'http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2017-08-01&format=text'

sap_storage_az_vmsize:

sap_storage_az_lun: '/dev/disk/azure/scsi1/lun'

# AWS variables

# should probably put into a platform specific vars file, to be included and overwriting the default
#sap_storage_setup_aws_nfs_options: 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,acl'

sap_storage_aws_imds_url:
sap_storage_aws_vmsize_url:

sap_storage_aws_vmsize:

# IBM Cloud variables
