---

  - name: SAP HANA Post Install - Include firewall specific vars
    ansible.builtin.include_vars: firewall_vars.yml
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Enable and start the firewalld service
    ansible.builtin.systemd:
      name: SAP HANA Post Install - firewalld
      state: started
      enabled: yes
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Construct the argument list for firewall-cmd
    ansible.builtin.set_fact:
      __sap_hana_install_fact_firewall_cmd_args:
        "{{ ['--add-port='] | product(firewall[0].port) | map('join') | list }}"
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Set fact for the firewall-cmd command
    ansible.builtin.set_fact:
      __sap_hana_install_fact_firewall_cmd_command:
        "firewall-cmd --zone=public {{ __sap_hana_install_fact_firewall_cmd_args | map('quote') | join(' ') }}"
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Display the firewall-cmd command
    ansible.builtin.debug:
      var: __sap_hana_install_fact_firewall_cmd_command
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Enable the required ports immediately
    ansible.builtin.command: "{{ __sap_hana_install_fact_firewall_cmd_command }}"
    tags: sap_hana_install_configure_firewall

  - name: SAP HANA Post Install - Enable the required ports permanently
    ansible.builtin.command: "{{ __sap_hana_install_fact_firewall_cmd_command }} --permanent"
    tags: sap_hana_install_configure_firewall
