---

- name: SAP HANA Post Install - Firewall Setup
  block:

    - name: SAP HANA Post Install - Gathering Firewall Facts
      package_facts:
        manager: auto

    - name: SAP HANA Post Install - Setup Firewall if included in packages
      block:

        - name: SAP HANA Post Install - Service firewalld state - enable
          command: "systemctl enable firewalld"

        - name: SAP HANA Post Install - Service firewalld state - start
          command: "systemctl start firewalld"

        - name: SAP HANA Post Install - Generate Ports Based on NR - {{ sap_hana_install_instance_number }}
          set_fact:
            sap_hana_firewall_ports:
              - "1128"
              - "1129"
              - "43{{ sap_hana_install_instance_number }}"
              - "5050"
              - "9090"
              - "9091"
              - "9092"
              - "9093"
              - "3{{ sap_hana_install_instance_number }}00-3{{ sap_hana_install_instance_number }}90"
              - "30105"
              - "30107"
              - "30140"
              - "4{{ sap_hana_install_instance_number }}01"
              - "4{{ sap_hana_install_instance_number }}02"
              - "4{{ sap_hana_install_instance_number }}06"
              - "4{{ sap_hana_install_instance_number }}12"
              - "4{{ sap_hana_install_instance_number }}14"
              - "4{{ sap_hana_install_instance_number }}40"
              - "5{{ sap_hana_install_instance_number }}00"
              - "5{{ sap_hana_install_instance_number }}13"
              - "5{{ sap_hana_install_instance_number }}14"
              - "51000"
              - "64997"

        - name: SAP HANA Post Install - Add Ports Based on NR - {{ sap_hana_install_instance_number }}
          include_tasks: update_firewall.yml
#          include_tasks: post_install_update_firewall.yml
          loop: "{{ sap_hana_firewall_ports }}"
          loop_control:
            loop_var: passed_port

        - name: SAP HANA Post Install - Reload Firewall
          shell: |
            firewall-cmd --reload

    # Stop firewall for now
        - name: SAP HANA Post Install - Service firewalld state - stop
          command: "systemctl stop firewalld"

      when:
        - '"firewalld" in ansible_facts.packages'

  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
