---
# task name prefix
__tname: "SAP HA Cluster -"

# TODO: Potentially make this role a wrapper for any SAP solution role to be configured
# in a pacemaker cluster.

# Variables for the cluster setup must be constructed by dedicated tasks!
# The included 'ha_cluster' role will not work with the role variables set
# in this role.

# TODO: make sure to first respect 'ha_cluster' native variables

sap_ha_cluster_cluster_nodes: "{{ sap_hana_cluster_nodes }}"
sap_ha_cluster_hana_sid: "{{ sap_hana_sid }}"
sap_ha_cluster_hana_instance_number: "{{ sap_hana_instance_number }}"
sap_ha_cluster_hana_instance_vip: "{{ sap_hana_vip }}"

# make sure that there is always the default fed into the included role
sap_ha_cluster_fence_agent_packages:
  - fence-agents-all


# The type of SAP landscape and multi-node replication
#sap_ha_cluster_sap_type: ""
sap_ha_cluster_replication_type: ""
