---

sap_anydb_install_oracle_prep_reboot_ok: yes

sap_anydb_install_oracle_prep_fail_if_reboot_required: no

sap_anydb_install_oracle_prep_precheck: no

# minimal, responsefile
sap_anydb_install_oracle_method: minimal

sap_anydb_install_oracle_sid: OR1

sap_anydb_install_oracle_base: /oracle

sap_anydb_install_oracle_filesystem_storage: /oradata

sap_anydb_install_oracle_inventory_central: /oraInventory

sap_anydb_install_oracle_system_password:

sap_anydb_install_oracle_extract_path: # e.g. /software

sap_anydb_patch_oracle_sbp_path:       # e.g. /SAP_CD/oracle/19.0/sbp/2311

sap_anydb_patch_oracle_opatch_zip:     # e.g. OPATCH19P_2308-70004508.ZIP

sap_anydb_patch_oracle_sap_zip:        # e.g. SAP19P_2311-70004508.ZIP
