---
# defaults file for sap_hana_rhv_hypervisor

#sap_hana_rhv_hypervisor_modify_grub_cmdline_linux: yes
sap_hana_rhv_hypervisor_run_grub2_mkconfig: yes

#sap_hana_rhv_hypervisor_rhv_specific_config: yes

# Reserve memory [GB] for hypervisor host
sap_hana_rhv_hypervisor_reserved_ram: 100

# allocate hugepages: {static|runtime} 
# static: done at kernel command line which is slow, but safe
# runtime: done through tuned-profile 
sap_hana_rhv_hypervisor_reserve_hugepages: static

# kvm.nx_huge_pages: {"auto"|"on"|"off"}
# Note the importance of the quotes, otherwise off will be mapped to false
sap_hana_rhv_hypervisor_kvm_nx_huge_pages: "auto"

# Intel Transactional Synchronization Extensions (TSX): {"on"|"off"}
# Note the importance of the quotes, otherwise off will be mapped to false
sap_hana_rhv_hypervisor_tsx: "off"

# fail if assertion is invalid
sap_hana_rhv_hypervisor_ignore_failed_assertion: no
