---
# This task requires the variable passed_port

- name: Update Firewall - {{ passed_port }}/tcp
  firewalld:
    zone: public
    port: "{{ passed_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
