---
galaxy_info:
  namespace: community
  author: Markus Koch, Thomas Bludau, Bernd Finger, Than Ngo, Rainer Leber
  description: Performs SAP HANA specific preparation steps on a RHEL or SLES system
  company: Red Hat, Inc.
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [ 7, 8, 9 ]
    - name: SLES
      versions: [ 15SP3 ]
  galaxy_tags: [ 'sap', 'hana', 'rhel', 'suse' ]
dependencies: []
