---
# The following tasks are only included on the primary node!

- name: "SAP Pacemaker Setup - Setup Pacemaker cluster"
  ansible.builtin.command: |
    pcs cluster setup \
    {{ sap_ha_install_pacemaker_cluster_name }} {% for node in sap_ha_install_pacemaker_cluster_nodes %}{{ node.node_name }}{{ " " if not loop.last else "" }}{% endfor %} \
    totem token=30000 \
    --enable --start --wait=30
  register: __sap_ha_install_pacemaker_cluster_create
  changed_when: __sap_ha_install_pacemaker_cluster_create.rc == 0

- name: "SAP Pacemaker Setup - Check cluster nodes are online"
  ansible.builtin.shell: |
    set -e -o pipefail
    pcs status nodes corosync | awk -F ':' '/Offline/{print $2}'
  args:
    executable: /usr/bin/bash
  register: __sap_ha_install_pacemaker_cluster_online
  failed_when:
    - __sap_ha_install_pacemaker_cluster_online.stderr|length != '0'
    - __sap_ha_install_pacemaker_cluster_online.stdout|length != '0'
  changed_when: false

#- name: "SAP Pacemaker Setup - Set Expected Votes = {{ sap_ha_install_pacemaker_cluster_nodes | length }}"
#  ansible.builtin.shell: |
#    pcs quorum expected-votes {{ sap_ha_install_pacemaker_cluster_nodes | length }}

- name: "SAP Pacemaker Setup - Check pcs properties"
  include_tasks: check_properties.yml

- name: "SAP Pacemaker Setup - Allow concurrent fence actions"
  ansible.builtin.shell: |
    pcs property set concurrent-fencing=true
  when:
    - "'concurrent-fencing: true' not in __sap_ha_install_pacemaker_pcs_properties.stdout"
