---
- name: Set role variables if not defined
  ansible.builtin.set_fact:
    sap_ha_install_pacemaker_hana_sid: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_hana_sid)|d('RH1') }}"
    sap_ha_install_pacemaker_site1_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site1_name)|d('DC1') }}"
    sap_ha_install_pacemaker_site2_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site2_name)|d('DC2') }}"
    sap_ha_install_pacemaker_site3_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site3_name)|d('DC3') }}"
    sap_ha_install_pacemaker_site4_name: "{{ sap_hana_sid|d(sap_ha_install_pacemaker_site4_name)|d('DC4') }}"
    sap_ha_install_pacemaker_node1_hostname: "{{ sap_hana_node1_hostname|d(sap_ha_install_pacemaker_node1_hostname)|d('hana01') }}"
    sap_ha_install_pacemaker_node2_hostname: "{{ sap_hana_node2_hostname|d(sap_ha_install_pacemaker_node2_hostname)|d('hana02') }}"
    sap_ha_install_pacemaker_instance_number: "{{ sap_hana_instance_number|d(sap_ha_install_pacemaker_instance_number)|d('00') }}"
  tags:
    - pacemaker
    - ha
    - stonith
  
- name: "SAP Pacemaker Part 2 - Check Cluster"
  tags: pacemaker
  ansible.builtin.shell: |
      pcs cluster status
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_install_pacemaker_check_cluster
  changed_when: false
  failed_when: false
  tags:
    - pacemaker
    - ha
  
- name: SAP Pacemaker Part 2 - Cluster Setup
  include_tasks: 
    file: cluster_setup.yml
    apply:
      tags:
        - pacemaker
        - ha
  when:
    - sap_ha_install_pacemaker_role == 'primary'
    - sap_ha_install_pacemaker_check_cluster.rc == 1
  tags:
    - pacemaker
    - ha

- name: SAP Pacemaker Part 2 - Stonith Configuration
  include_tasks: 
    file: stonith_config.yml
    apply:
      tags: 
        - stonith
        - pacemaker
        - ha
  when:
    - sap_ha_install_pacemaker_role == 'primary'
  tags: 
    - stonith
    - ha
    - pacemaker
