# [A] - runs on both node 1 and 2 / primary secondary
# [1] - runs on node 1 / primary
# [2] - runs on node 2 / secondary

# [A] Disable firewall

- name: SAP Pacemaker Setup - [A] Disable firewall
  include_tasks: disable_firewall.yml
  
# Part 1
# Installs the necessary software and preconfiguration

- name: SAP Pacemaker Part 1 - Software Setup
  include_tasks: software_setup.yml
  when:
    - sap_ha_install_pacemaker_part == '1'

- name: SAP Pacemaker Part 1 - Preconfig
  include_tasks: preconfig.yml
  when:
    - sap_ha_install_pacemaker_part == '1'

# Part 2
# Cluster Setup, Service Principal, Stonith Configuration

- name: SAP Pacemaker Part 2 - Cluster Setup
  include_tasks: cluster_setup.yml
  when:
    - sap_ha_install_pacemaker_part == '2'

# Service principal setup is in TF
#- name: SAP Pacemaker Part 2 - Service Principal
#  include_tasks: service_principal.yml
#  when:
#    - sap_ha_install_pacemaker_part == '2'

- name: SAP Pacemaker Part 2 - Stonith Configuration
  include_tasks: stonith_config.yml
  when:
    - sap_ha_install_pacemaker_part == '2'

