---

# [A] Change hacluster password
- name: SAP Pacemaker Setup - [A] Ensure password for hacluster is configured
  shell: |
        echo '{{ sap_ha_install_pacemaker_hacluster_password }}' | passwd --stdin hacluster
# # [A] Change hacluster password
# - name: Ensure password for hacluster is configured
#   user:
#     name: hacluster
#     password: "{{ sap_ha_install_pacemaker_hacluster_password | password_hash('sha512') }}"

# [A] Enable basic cluster services
- name: SAP Pacemaker Setup - [A] Enable basic cluster services
  shell: |
    systemctl start pcsd.service
    systemctl enable pcsd.service

# [A] Update /etc/hosts

# - name: SAP Pacemaker Setup - [A] Update /etc/hosts
#   include_tasks: update_etchosts.yml