---


- name: SAP Pacemaker Setup - [A] Subscription Manager - Clean
  command: 'subscription-manager clean' 

- name: SAP Pacemaker Setup - [A] Subscription Manager - Remove
  command: 'subscription-manager remove --all'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Register
  command: 'subscription-manager register --force --username={{ sap_rhsm_username }} --password="{{ sap_rhsm_password }}"'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Identity Regenerate
  command: 'subscription-manager identity --regenerate --force --username={{ sap_rhsm_username }} --password="{{ sap_rhsm_password }}"'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Auto Attach
  command: 'subscription-manager auto-attach'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Attach Pool
  command: 'subscription-manager attach --pool="{{ sap_rhsm_pools_id }}"'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Lock Release
  command: 'subscription-manager release --set={{ ansible_distribution_version }}'

- name: SAP Pacemaker Setup - [A] Subscription Manager - Disable Repos
  command: 'subscription-manager repos --disable="*"'

# Enable Repos
- name: SAP Pacemaker Setup - [A] Subscription Manager - Enable RHEL HA Repos
  command: 'subscription-manager repos --enable="{{ item }}"'
  with_items: "{{ sap_ha_install_pacemaker_rhsm_repos }}"

# Install Packages
- name: SAP Pacemaker Setup - [A] Install Packages
  command: 'yum -y install {{ item }}'
  with_items: "{{ sap_ha_install_pacemaker_packages }}"

# Install Packages - Vendor Specific
- name: SAP Pacemaker Setup - [A] Install Packages - Vendor Specific
  command: 'yum -y install {{ item }}'
  with_items: "{{ vars['sap_ha_install_pacemaker_packages_' + sap_ha_install_pacemaker_type] }}"

- name: SAP Pacemaker Setup - [A] Yum clean all
  command: 'yum clean all'
  args:
    warn: false
    
- name: SAP Pacemaker Setup - [A] Yum search sap-
  command: 'yum -y search sap-'

- name: SAP Pacemaker Setup - [A] Clear dnf cache
  file:
    path: /var/cache/dnf
    state: absent

- name: SAP Pacemaker Setup - [A] Clear rhsm packages
  file:
    path: /var/lib/rhsm/packages/packages.json
    state: absent

- name: SAP Pacemaker Setup - [A] Restart service rhsmcertd
  service:
    name: rhsmcertd
    state: restarted

# - name: SAP Pacemaker Setup - [A] Install Azure CLI
#   shell: |
#     rpm --import https://packages.microsoft.com/keys/microsoft.asc
#     echo -e "[azure-cli]
#     name=Azure CLI
#     baseurl=https://packages.microsoft.com/yumrepos/azure-cli
#     enabled=1
#     gpgcheck=1
#     gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo
#     sudo dnf -y install azure-cli
#   when:
#     - sap_ha_install_pacemaker_type == 'az'