---
# Create the STONITH devices
- name: "Update STONITH timeout"
  shell: |
    pcs property set stonith-timeout=900
  register: pcs_property_set_stonith_timeout
  when:
    - sap_ha_install_pacemaker_role == 'primary'

# Generic fence device configuration
- name: "Check the fence device"
  shell: |
    pcs stonith config 
  register: sap_ha_install_pacemaker_stonith_check
  when:
    - sap_ha_install_pacemaker_role == 'primary'

# Generic fence device configuration
- name: "Configure the fence device"
  shell: |
    pcs stonith create \
    {{ sap_ha_install_pacemaker_stonith_name }} {{ sap_ha_install_pacemaker_stonith_fence_agent }} \
    {{ sap_ha_install_pacemaker_stonith_credential }} \
    {{ sap_ha_install_pacemaker_stonith_parameters }}
  when:
    - sap_ha_install_pacemaker_role == 'primary'
    - sap_ha_install_pacemaker_stonith_name in sap_ha_install_pacemaker_stonith_check.stdout

# Enable the use of a STONITH device
- name: "Enable the STONITH devices"
  shell: |
    pcs property set stonith-enabled=true
  register: pcs_property_set_stonith_enabled
  when:
    - sap_ha_install_pacemaker_role == 'primary'

## Example for azure-arm fence device configuration
#- name: Configure the fence device
#  shell: |
#    pcs stonith create {{ sap_ha_install_pacemaker_stonith_name }} {{ sap_ha_install_pacemaker_stonith_fence_agent }} \
#    username="{{ sap_ha_install_pacemaker_client_id }}" password="{{ sap_ha_install_pacemaker_client_secret }}" \
#    resourceGroup="{{ sap_ha_install_pacemaker_resource_group }}" tenantId="{{ sap_ha_install_pacemaker_tenant_id }}" \
#    subscriptionId="{{ sap_ha_install_pacemaker_subscription_id }}" \
#    pcmk_host_map="{{ sap_ha_install_pacemaker_node1_hostname }}:{{ sap_ha_install_pacemaker_node1_hostname }};{{ sap_ha_install_pacemaker_node2_hostname }}:{{ sap_ha_install_pacemaker_node2_hostname }}" \
#    power_timeout=240 pcmk_reboot_timeout=900 pcmk_monitor_timeout=120 pcmk_monitor_retries=4 pcmk_action_limit=3 pcmk_delay_max=15 \
#    op monitor interval=3600
#  register: pcs_stonith_create
#  when:
#    - sap_ha_install_pacemaker_role == 'primary'
#    - sap_ha_install_pacemaker_stonith_fence_agent == 'fence-agents-azure-arm'
##     pcmk_host_map="prod-cl1-0:prod-cl1-0-{{ sap_hana_ha_pacemaker_node1_hostname }};prod-cl1-1:prod-cl1-1-{{ sap_hana_ha_pacemaker_node2_hostname }}" \
