- name:  SAP SWPM - {{ sap_swpm_swpm_installation_header }}
  command: >-
    ./sapinst \
    {{ sap_swpm_swpm_command_inifile }} \
    {{ sap_swpm_swpm_command_product_id }} \
    {{ sap_swpm_swpm_command_extra_args }}
  register: sap_swpm_installswpm_reg
  args:
    chdir: "{{ sap_swpm_sapinst_path }}"
  changed_when: "'SAPinst build information' in sap_swpm_installswpm_reg.stdout"
