---

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#

# 29Nov2023_itdose2023: create block "marcelmamula: redundant when conditionals should be replaced by blocks with single when condition to remove clutter"
- name: prepare saptune
  block:
    # 12Nov2023_itdose2023: add when Statement for saptune
    - name: Ensure saptune is running and enabled
      ansible.builtin.systemd:
        name: saptune
        state: started
        enabled: yes
        
    # 12Nov2023_itdose2023: add when Statement for saptune
    - name: Ensure saptune_check executes correctly
      ansible.builtin.command: saptune_check
      changed_when: no

    # 12Nov2023_itdose2023: Add this section for sapconf:  
    - name: Discover active solution
      ansible.builtin.command: saptune solution enabled
      register: __sap_hana_preconfigure_register_saptune_status
      changed_when: no

    # 12Nov2023_itdose2023: Add this section for sapconf:
    - name: Set fact for active solution
      ansible.builtin.set_fact:
        __sap_hana_preconfigure_fact_solution_configured: "{{ (__sap_hana_preconfigure_register_saptune_status.stdout | regex_search('(\\S+)', '\\1'))[0] | default('NONE') }}" # Capture the first block on none whitespace

    # 12Nov2023_itdose2023: Add this section for sapconf:
    - name: Show configured solution
      ansible.builtin.debug:
        var: __sap_hana_preconfigure_fact_solution_configured
  when: 
    __sap_hana_preconfigure_run_saptune

# 12Nov2023_itdose2023: Add this section for sapconf:
- name: Ensure sapconf is running and enabled
  ansible.builtin.systemd:
    name: sapconf
    state: started
    enabled: yes
  when:
    not __sap_hana_preconfigure_run_saptune

# If this is a cluster node on Azure, we need to override to disable tcp timestamps, reuse and recycle.
# This can be done by copying the sapnote file 2382421 from /usr/share/saptune/notes to /etc/saptune/override
# The value can then override in the in the new file

- name: Disable TCP timestamps, recycle & reuse
  ansible.builtin.blockinfile:
    path: /etc/saptune/override/2382421
    create: yes
    backup: yes
    owner: root
    group: root
    mode: '0640'
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
     [sysctl]
     net.ipv4.tcp_timestamps = 0
     net.ipv4.tcp_tw_reuse = 0
     net.ipv4.tcp_tw_recycle = 0
  when:
    - sap_hana_preconfigure_saptune_azure

- name: Check if saptune solution needs to be applied
  ansible.builtin.command: "saptune solution verify {{ sap_hana_preconfigure_saptune_solution }}"
  register: __sap_hana_preconfigure_register_saptune_verify
  changed_when: no # We're only checking, not changing!
  failed_when: no # We expect this to fail if it has not previously been applied
  when: 
    __sap_hana_preconfigure_run_saptune

- name: Ensure no solution is currently applied
  ansible.builtin.command: "saptune solution revert {{ __sap_hana_preconfigure_fact_solution_configured }}"
  when:
    - __sap_hana_preconfigure_run_saptune
    - __sap_hana_preconfigure_fact_solution_configured != 'NONE'
    - __sap_hana_preconfigure_register_saptune_verify.rc != 0
   

- name: Ensure saptune solution is applied
  ansible.builtin.command: "saptune solution apply {{ sap_hana_preconfigure_saptune_solution }}"
  when: 
    - __sap_hana_preconfigure_run_saptune
    - __sap_hana_preconfigure_register_saptune_verify.rc != 0

# 29Nov2023_itdose2023: create block "marcelmamula: redundant when conditionals should be replaced by blocks with single when condition to remove clutter"
- name: saptune verification
  block:
    - name: Ensure solution was successful
      ansible.builtin.command: "saptune solution verify {{ sap_hana_preconfigure_saptune_solution }}"
      changed_when: no # We're only checking, not changing!

    - name: Make sure that sapconf and tuned are stopped and disabled
      ansible.builtin.command: "saptune service takeover"
      register: __sap_saptune_takeover
      changed_when: __sap_saptune_takeover.rc == 0
  when: 
    - __sap_hana_preconfigure_run_saptune

# 12Nov2023_itdose2023: In case sapconf is used (Standard SLES), start Service
- name: restart sapconf service 
  ansible.builtin.systemd:
    name: sapconf
    state: restarted
  when:
    not __sap_hana_preconfigure_run_saptune
