---
#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
# Reason for noqa: Both yum and dnf support "state: latest"
- name: Ensure that the system is updated to the latest patchlevel # noqa package-latest
  ansible.builtin.package:
    state: latest
    name: "*"
  when: sap_hana_preconfigure_update | bool

# 12Nov2023_itdose2023: add when Statement for saptune because sap-hana is not available on Standard SLES
- name: Ensure saphana pattern is installed
  community.general.zypper:
    type: pattern
    name: sap-hana
    state: present
    force: yes
  when: 
    __sap_hana_preconfigure_run_saptune

# 12Nov2023_itdose2023: add when Statement for saptune
- name: Ensure saptune is installed
  community.general.zypper:
    type: package
    name: "saptune={{ sap_hana_preconfigure_saptune_version }}"
    state: present
    force: yes
  when: 
    __sap_hana_preconfigure_run_saptune

# 12Nov2023_itdose2023: Add this section for sapconf:
- name: Ensure sapconf is installed
  community.general.zypper:
    type: package
    name: "sapconf"
    state: present
    force: yes
  when: 
    not __sap_hana_preconfigure_run_saptune