---
#sap_ha_pacemaker_cluster_vip_resource_name: "vip_{{ sap_ha_pacemaker_cluster_netweaver_sid }}"

# List of ASCS/ERS profile names.
# Used in tasks/configure_netweaver_postinstallation.yml for sap_cluster_connector setup.
__sap_ha_pacemaker_cluster_netweaver_abap_ascs_ers_profile_paths:
  - "{{ sap_ha_pacemaker_cluster_netweaver_abap_ascs_sapinstance_start_profile_string }}"
  - "{{ sap_ha_pacemaker_cluster_netweaver_abap_ers_sapinstance_start_profile_string }}"
