---
# Variables specific on IBM Power hypervisor
# TODO: rename this file to match the actual "chassis_asset_tag" output
# TODO: make sure to first respect 'ha_cluster' native variables
sap_ha_pacemaker_cluster_fence_agent_packages:
  - fence-agents-ibm-powervs
