---

- name: Ensure required packages for SAP NetWeaver are installed
  ansible.builtin.package:
    state: present
    name: "{{ __sap_netweaver_preconfigure_packages }}"

# 29Nov2023_itdose2023: Add recommendation to set variable based on installed OS
- name: Get contents of /etc/products.d/baseproduct
  ansible.builtin.stat:
    path: /etc/products.d/baseproduct
  register: sles_baseproduct
  when: ansible_os_family == 'Suse'

- name: Setfact if baseproduct contains SLES without SLES_SAP
  ansible.builtin.set_fact:
    __sap_netweaver_preconfigure_run_saptune: false
  when: 
    - '"SLES_SAP" not in sles_baseproduct.stat.lnk_target'
    - '"SLES" in sles_baseproduct.stat.lnk_target'
    - ansible_os_family == 'Suse'

# 12Nov2023_itdose2023: Add when Statement
#The use of zypper here allows exact saptune version to be declared and used.
- name: Ensure saptune is installed
  community.general.zypper:
    type: package
    name: "saptune={{ sap_netweaver_preconfigure_saptune_version }}"
    state: present
    force: yes
  when:
    __sap_netweaver_preconfigure_run_saptune

# 12Nov2023_itdose2023: Add sapconf Section
- name: Ensure sapconf is installed
  community.general.zypper:
    type: package
    name: "sapconf"
    state: present
    force: yes
  when:
    not __sap_netweaver_preconfigure_run_saptune