---
- name: SAP Pacemaker Setup - Start pcsd.service
  ansible.builtin.systemd:
    name: pcsd.service
    state: started

# [1] Authenticate Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Authenticate primary cluster node
  ansible.builtin.shell: |
    pcs host auth \
    {{ sap_ha_prepare_pacemaker_node1_hostname }} \
    -u hacluster -p '{{ sap_ha_prepare_pacemaker_hacluster_password }}'
  register: pcs_host_auth_reg
  when:
    - sap_ha_prepare_pacemaker_role == 'primary'

# [1] Authenticate Pacemaker cluster
- name: SAP Pacemaker Setup - [1] Authenticate secondary cluster node
  ansible.builtin.shell: |
    pcs host auth \
    {{ sap_ha_prepare_pacemaker_node2_hostname }} \
    -u hacluster -p '{{ sap_ha_prepare_pacemaker_hacluster_password }}'
  register: pcs_host_auth_reg
  when:
    - sap_ha_prepare_pacemaker_role == 'secondary'
  delegate_to: "{{ sap_ha_prepare_pacemaker_node1_hostname }}"
