---
- name: "SAP Prepare Pacemaker - Set role variables if not defined"
  ansible.builtin.set_fact:
    sap_ha_prepare_pacemaker_site1_name: "{{ sap_hana_sid|d(sap_ha_prepare_pacemaker_site1_name)|d('DC1') }}"
    sap_ha_prepare_pacemaker_site2_name: "{{ sap_hana_sid|d(sap_ha_prepare_pacemaker_site2_name)|d('DC2') }}"
    sap_ha_prepare_pacemaker_site3_name: "{{ sap_hana_sid|d(sap_ha_prepare_pacemaker_site3_name)|d('DC3') }}"
    sap_ha_prepare_pacemaker_site4_name: "{{ sap_hana_sid|d(sap_ha_prepare_pacemaker_site4_name)|d('DC4') }}"
    sap_ha_prepare_pacemaker_node1_hostname: "{{ sap_hana_node1_hostname|d(sap_ha_prepare_pacemaker_node1_hostname)|d('hana01') }}"
    sap_ha_prepare_pacemaker_node2_hostname: "{{sap_hana_node2_hostname|d(sap_ha_prepare_pacemaker_node2_hostname)|d('hana02') }}"
  tags:
    - ha_software
    - ha_firewall
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Check if pcs package is installed"
  shell: |
      rpm -qa pcs
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_prepare_pacemaker_check_pcs
  changed_when: false
  tags:
    - ha_software
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Software Setup"
  include_tasks: 
    files: software_setup.yml
    apply:
      tags:
        - ha_software
        - pacemaker
        - ha
  when:
    - sap_ha_prepare_pacemaker_check_pcs.rc != '0'
  tags:
    - ha_software
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Preconfig"
  include_tasks: 
    files: preconfig.yml
    apply:
      tags:
        - pacemaker
        - ha
  tags:
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Include Firewall Tasks"
  include_tasks:
    file: configure_firewall.yml
    apply:
      tags: 
        - ha_firewall
        - pacemaker
        - ha
  when:
    - (sap_hana_configure_firewall is defined and sap_hana_configure_firewall) or
      sap_ha_prepare_pacemaker_configure_firewall
  tags:
    - ha_firewall
    - pacemaker
    - ha

- name: "SAP Prepare Pacemaker - Check Cluster Status"
  shell: |
      pcs cluster status
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: sap_ha_prepare_pacemaker_check_cluster
  changed_when: false # '"Cluster Name" in sap_ha_prepare_pacemaker_check_cluster.stdout'
  failed_when: false
  tags:
    - pacemaker
    - ha
  
- name: "SAP Prepare Pacemaker - Cluster Prepare"
  include_tasks: 
    files: cluster_prepare.yml
    apply:
      tags:
        - pacemaker
        - ha
  when:
    - sap_ha_prepare_pacemaker_check_cluster.rc == 1
  tags:
    - pacemaker
    - ha
