---

- name: SAP Install Media Detect - Oracle DB - Set fact for install media directory
  set_fact:
    oracledb_install_directory: "{{ sap_install_media_detect_directory }}/oracledb"
    oracledb_client_install_directory: "{{ sap_install_media_detect_directory }}/oracledb_client"

- name: SAP Install Media Detect - Oracle DB - Create Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ oracledb_install_directory }}"
    - "{{ oracledb_client_install_directory }}"

- name: List files in directory
  ansible.builtin.shell: ls -1
  register: detect_directory_files
  args:
    chdir: "{{ sap_install_media_detect_directory }}"

- name: Detect ZIP files (including no file extensions), ignore errors
  ansible.builtin.shell: if [ ! -z "$(file {{ item }} | grep 'Zip archive data')" ]; then echo {{ item }}; fi
  register: detect_directory_files_zip
#  changed_when: "item.stdout | length > 0"
  with_items: 
    - "{{ detect_directory_files.stdout_lines }}"
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
  ignore_errors: true

- name: Identify Oracle DB installation media
  ansible.builtin.shell: |
    if [ ! -z "$(file {{ item }} | grep 'Zip archive data')" ]; then if zipinfo -1 {{ item }} | grep -q '19cinstall.sh' ; then echo '{{ item }}' ; fi ; fi
  register: detect_directory_files_oracledb
  changed_when: "item | length > 0"
  with_items: 
    - "{{ detect_directory_files_zip.results | map(attribute='stdout') | select() }}"
  args:
    chdir: "{{ sap_install_media_detect_directory }}"

- name: Identify Oracle DB Client installation media
  ansible.builtin.shell: |
    if [ ! -z "$(file {{ item }} | grep 'Zip archive data')" ]; then if zipinfo -1 {{ item }} | grep -q 'OCL_LINUX_X86_64' ; then echo '{{ item }}' ; fi ; fi
  register: detect_directory_files_oracledb_client
  changed_when: "item | length > 0"
  with_items: 
    - "{{ detect_directory_files_zip.results | map(attribute='stdout') | select() }}"
  args:
    chdir: "{{ sap_install_media_detect_directory }}"

- name: Extract ZIP files of Oracle DB installation media
  ansible.builtin.shell: if [ ! -z "$(file {{ item }} | grep 'Zip archive data')" ]; then unzip {{ item }} -d {{ oracledb_install_directory }}/{{ item }}_extracted; fi
  with_items: 
    - "{{ detect_directory_files_oracledb.results | map(attribute='stdout') | select() }}"
  args:
    chdir: "{{ sap_install_media_detect_directory }}"

- name: Extract ZIP files of Oracle DB Client installation media
  ansible.builtin.shell: if [ ! -z "$(file {{ item }} | grep 'Zip archive data')" ]; then unzip {{ item }} -d {{ oracledb_install_directory }}/{{ item }}_extracted; fi
  with_items: 
    - "{{ detect_directory_files_oracledb_client.results | map(attribute='stdout') | select() }}"
  args:
    chdir: "{{ sap_install_media_detect_directory }}"
