---

- name: SAP Install Media Detect - Prepare - Provide sapfile utility
  ansible.builtin.include_tasks:
    file: prepare/provide_sapfile_utility.yml
    apply:
      tags: sap_install_media_detect_provide_sapfile_utility
  tags: sap_install_media_detect_provide_sapfile_utility

- name: SAP Install Media Detect - Prepare - Enable rar handling
  ansible.builtin.include_tasks:
    file: prepare/enable_rar_handling.yml
    apply:
      tags: sap_install_media_detect_rar_handling
  tags: sap_install_media_detect_rar_handling

- name: SAP Install Media Detect - Prepare - Check directories
  ansible.builtin.include_tasks:
    file: prepare/check_directories.yml
    apply:
      tags: sap_install_media_detect_check_directories
  tags: sap_install_media_detect_check_directories

- name: SAP Install Media Detect - Create a list of all files, phase 1
  ansible.builtin.include_tasks:
    file: prepare/create_file_list_phase_1.yml
    apply:
      tags: sap_install_media_detect_create_file_list_phase_1
  tags: sap_install_media_detect_create_file_list_phase_1

- name: SAP Install Media Detect - Detect and if necessary rename zip and rar files without extension
  ansible.builtin.include_tasks:
    file: rename/add_file_extension.yml
    apply:
      tags: sap_install_media_detect_add_file_extension
  tags: sap_install_media_detect_add_file_extension

- name: SAP Install Media Detect - Create a list of all required files, phase 2
  ansible.builtin.include_tasks:
    file: prepare/create_file_list_phase_2.yml
    apply:
      tags: sap_install_media_detect_create_file_list_phase_2
  tags: sap_install_media_detect_create_file_list_phase_2

- name: SAP Install Media Detect - Organize files
  ansible.builtin.include_tasks:
    file: organize_files.yml
    apply:
      tags: sap_install_media_detect_organize_files
  tags: sap_install_media_detect_organize_files

- name: SAP Install Media Detect - Find files after extraction
  ansible.builtin.include_tasks:
    file: find_files_after_extraction.yml
    apply:
      tags: sap_install_media_detect_find_files_after_extraction
  tags: sap_install_media_detect_find_files_after_extraction

- name: SAP Install Media Detection Completed - Set global vars for subsequent Ansible tasks or roles
  ansible.builtin.include_tasks:
    file: set_global_vars.yml
    apply:
      tags: sap_install_media_detect_set_global_vars
  tags: sap_install_media_detect_set_global_vars

- name: SAP Install Media Detection Completed - Cleanup - Disable the EPEL repo if necessary
  ansible.builtin.include_tasks:
    file: cleanup/disable-epel-repo.yml
    apply:
      tags: sap_install_media_detect_rar_handling
  tags: sap_install_media_detect_rar_handling
  when:
    - sap_install_media_detect_rar_package == 'EPEL'
    - __sap_install_media_detect_register_rpm_q_epel.stdout != 'epel-release'

- name: SAP Install Media Detect - Cleanup - Remove sapfile utility
  ansible.builtin.include_tasks:
    file: cleanup/remove_sapfile_utility.yml
    apply:
      tags: sap_install_media_detect_provide_sapfile_utility
  tags: sap_install_media_detect_provide_sapfile_utility
