---

- name: SAP Install Media Detection Completed - set facts for SAP HANA
  ansible.builtin.set_fact:
    sap_hana_install_software_directory: "{{ sap_hana_install_directory }}" # for sap_hana_install Ansible Role
    sap_hana_install_software_extract_directory: "{{ sap_hana_install_directory }}/extracted" # for sap_hana_install Ansible Role
    sap_swpm_cd_rdms_path: "{{ sap_hana_client_path.files[0].path }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_db == "saphana"

- name: SAP Install Media Detection Completed - set facts for IBM Db2
  ansible.builtin.set_fact:
    sap_swpm_cd_ibmdb2_path: "{{ ibmdb2_install_directory }}/{{ softwarecenter_search_list_ecc_ibmdb2[0] }}_extracted" # for sap_swpm Ansible Role
    sap_swpm_cd_ibmdb2_client_path: "{{ ibmdb2_client_install_directory }}/{{ softwarecenter_search_list_ecc_ibmdb2_client[0] }}_extracted" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_db == "ibmdb2"

- name: SAP Install Media Detection Completed - set facts for Oracle DB
  ansible.builtin.set_fact:
    sap_swpm_cd_oracle_path: "{{ oracledb_install_directory }}/{{ softwarecenter_search_list_ecc_oracledb[0] }}_extracted" # for sap_swpm Ansible Role
    sap_swpm_cd_oracle_client_path: "{{ oracledb_client_find_dir.files[0].path }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_db == "oracledb"

- name: SAP Install Media Detection Completed - set facts for SAP ASE
  ansible.builtin.set_fact:
    sap_swpm_cd_sapase_path: "{{ sapase_find_dir.files[0].path }}" # for sap_swpm Ansible Role
    sap_swpm_cd_sapase_client_path: "{{ sapase_client_install_directory }}/{{ softwarecenter_search_list_ecc_sapase_client[0] }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_db == "sapase"

- name: SAP Install Media Detection Completed - set facts for SAP MaxDB
  ansible.builtin.set_fact:
    sap_swpm_cd_sapmaxdb_path: "{{ sapmaxdb_find_dir.files[0].path }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_db == "sapmaxdb"

- name: SAP Install Media Detection Completed - set facts for Export of SAP ECC
  ansible.builtin.set_fact:
    sap_swpm_cd_export_path: "{{ detect_directory_export_extracted.files[0].path }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_export == "ecc"

- name: SAP Install Media Detection Completed - set facts for Export of SAP S/4HANA
  ansible.builtin.set_fact:
    sap_swpm_cd_export_path: "{{ sap_swpm_s4hana_export_path }}/{{ softwarecenter_search_list_s4hana_export[0] | regex_replace('_.*', '') }}" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_export == "s4hana"

- name: SAP Install Media Detection Completed - set facts for SAP SWPM
  ansible.builtin.set_fact:
    sap_swpm_sapcar_path: "{{ sap_install_media_detect_directory }}/sap_swpm" # for sap_swpm Ansible Role
  ignore_errors: true
  when:
    - sap_install_media_detect_swpm == true
