---

# Determine Installation Type
- name: SAP SWPM default mode - Determine Installation Type
  ansible.builtin.include_tasks: "../pre_install/install_type.yml"

# Password Facts
- name: SAP SWPM default mode - Password Facts
  ansible.builtin.include_tasks: ../pre_install/password_facts.yml

# Prepare Software
- name: SAP SWPM default mode - Prepare Software
  ansible.builtin.include_tasks: prepare_software.yml

# Process SWPM Configfile Template
- name: SAP SWPM default mode - Process SWPM Configfile Template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    mode: '0640'
  register: sap_swpm_cftemplate
