---
# defaults file for sap_hana_rhv_guest

sap_hana_rhv_guest_run_grub2_mkconfig: yes

# Intel Transactional Synchronization Extensions (TSX): {"on"|"off"}
# Note the importance of the quotes, otherwise off will be mapped to false
sap_hana_rhv_guest_tsx: "on"

# run role in assert mode?
sap_hana_rhv_guest_assert: false

# fail if assertion is invalid
sap_hana_rhv_guest_ignore_failed_assertion: no
