---
argument_specs:
  main:
    short_description: SAP HANA Installation
    options: # List of variables
      sap_hana_install_sid:
        description: HANA SID
        type: str # str, list, dict, bool, int, float, path, raw, jsonarg, json, bytes, bits
        required: true
        no_log: true
      sap_hana_install_instance_number:
        description: HANA Instance Number
        type: str # str, list, dict, bool, int, float, path, raw, jsonarg, json, bytes, bits
        required: true
        no_log: true
