---
- name: Label nodes
  ansible.builtin.command: "oc label node {{ __sap_hypervisor_node_preconfigure_register_worker.name }} \
                            feature.node.kubernetes.io/cpu-feature-invtsc=true --overwrite=true"
  register: __sap_hypervisor_node_preconfigure_register_label_node
  changed_when: __sap_hypervisor_node_preconfigure_register_label_node.rc != 0

- name: Enable CPU Manager by patching MCP of "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
        labels:
          custom-kubelet: "cpumanager-enabled"

- name: Create kubletconfig for cpumanager "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: "cpumanager-enabled"
        kubernetes.io/hostname: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
        machineconfiguration.openshift.io/role: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: "cpumanager-enabled"
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s
          reservedSystemCPUs: "{{ sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus }}"

- name: Create kubletconfig for cpumanager "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is not defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: "cpumanager-enabled"
        kubernetes.io/hostname: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
        machineconfiguration.openshift.io/role: "{{ __sap_hypervisor_node_preconfigure_register_worker.name }}"
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: "cpumanager-enabled"
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s

- name: Label nodes
  ansible.builtin.command: "oc label node {{ __sap_hypervisor_node_preconfigure_register_worker.name }} cpumanager=true --overwrite=true"
  register: __sap_hypervisor_node_preconfigure_register_label_node
  changed_when: __sap_hypervisor_node_preconfigure_register_label_node.rc != 0
