---
- name: Gather Facts
  ansible.builtin.gather_facts:

- name: Create Tempdir
  ansible.builtin.tempfile:
    state: directory
    suffix: "_sap_hypervisor_node_preconfigure"
  register: __sap_hypervisor_node_preconfigure_register_tmpdir
