---
- name: Include configure kargs
  ansible.builtin.include_tasks: configure-kargs-per-node.yml
  with_items: "{{ __sap_hypervisor_node_preconfigure_register_nodes }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_register_worker
    index_var: __sap_hypervisor_node_preconfigure_register_worker_nr

- name: Include configure worker
  ansible.builtin.include_tasks: configure-worker-node.yml
  with_items: "{{ sap_hypervisor_node_preconfigure_cluster_config.workers }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_register_worker
    index_var: __sap_hypervisor_node_preconfigure_register_worker_nr

- name: Enable CPU Manager by patching MCP worker
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: worker
        labels:
          custom-kubelet: cpumanager-enabled


- name: Create kubletconfig for cpumanager worker
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is defined
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s
          reservedSystemCPUs: "{{ sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus }}"

- name: Create kubletconfig for cpumanager worker
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s
          reservedSystemCPUs: "{{ sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus }}"

- name: Create kubletconfig for cpumanager worker
  when: sap_hypervisor_node_preconfigure_cluster_config.worker_kubernetes_reserved_cpus is not defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: cpumanager-enabled
        machineconfiguration.openshift.io/role: worker
      spec:
        machineConfigPoolSelector:
          matchLabels:
            custom-kubelet: cpumanager-enabled
        kubeletConfig:
          cpuManagerPolicy: static
          cpuManagerReconcilePeriod: 5s
