---
sap_ha_prepare_pacemaker_hacluster_password: "{{ sap_hana_hacluster_password }}"
sap_ha_prepare_pacemaker_cluster_nodes: "{{ sap_hana_cluster_nodes }}"
sap_ha_prepare_pacemaker_configure_firewall: no

sap_ha_prepare_pacemaker_rhsm_repos:
  - "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rpms"

sap_ha_prepare_pacemaker_packages:
  - pcs
  - pacemaker
  - nfs-utils
  - resource-agents-sap-hana
  - fence-agents-all

# AZ specific definitions
sap_ha_prepare_pacemaker_client_id: ""
sap_ha_prepare_pacemaker_client_secret: ""
sap_ha_prepare_pacemaker_tenant_id: ""
sap_ha_prepare_pacemaker_resource_group: ""
sap_ha_prepare_pacemaker_subscription_id: ""

sap_ha_prepare_pacemaker_rhsm_repos_az:
  - rhel-7-server-rpms
  - rhel-ha-for-rhel-7-server-rpms
  - rhel-sap-for-rhel-7-server-rpms
  - rhel-ha-for-rhel-7-server-eus-rpms

sap_ha_prepare_pacemaker_packages_az:
  - fence-agents-azure-arm
  - nmap-ncat
