---

# Ansible does not support streaming of stdout, so we offer a workaround.
# For more information, see https://github.com/ansible/proposals/issues/92
- name: Copy file tail-f-hdblcm-install-trc.sh to '{{ __sap_hana_install_register_tmpdir.path }}'
  copy:
    src: tmp/tail-f-hdblcm-install-trc.sh
    dest: "{{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
    owner: root
    group: root
    mode: '0755'

# Show how to use the workaround:
- name: Show how to watch the install process in real time
  debug:
    msg:
      - 'Once the task "Installing SAP HANA" has started, you can use the following command'
      - 'in a terminal session on {{ inventory_hostname }} to watch the install progress in real time:'
      - "{{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
      - 'Alternatively, you can run the following command on the control node:'
      - "ssh {{ inventory_hostname }} {{ __sap_hana_install_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"

- name: Installing SAP HANA - {{ sap_hana_install_sid }} {{ sap_hana_install_instance_number }}
  command: "./hdblcm {{ sap_hana_install_hdblcm_extraargs }}
            --configfile={{ __sap_hana_install_register_tmpdir.path }}/configfile.cfg
            -b"
  register: __sap_hana_install_register_hdblcm_install
  args:
    chdir: "{{ sap_hana_hdblcm_path }}"
  changed_when: "'SAP HANA Lifecycle Management' in __sap_hana_install_register_hdblcm_install.stdout"
