---

- name: Warn if the role is used without specifying SAPCAR executable and SAR files
  debug:
    msg: "WARN: The role is used without variables 'sap_hana_install_sapcar_file'
          or 'sap_hana_install_sarfiles' being configured, so the SAPCAR executable
          and the SAR files in directory {{ sap_hana_install_software_directory }}
          will be determined automatically."
  when: sap_hana_install_sapcar_file is undefined or
        sap_hana_install_sarfiles is undefined

- import_tasks: hana_exists.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: pre_install.yml

- import_tasks: hana_install.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: hana_addhosts.yml
  when: not sap_hana_install_new_system|d(true)

- import_tasks: post_install.yml
