---

- import_tasks: hana_exists.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: pre_install.yml
  tags: sap_hana_install_tag_preinstall_only

- import_tasks: hana_install.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: hana_addhosts.yml
  when: not sap_hana_install_new_system|d(true)

- import_tasks: post_install.yml
