---

- name: Notify if the role is used without specifying the SAPCAR executable
  debug:
    msg: "INFO: The role is used without variable 'sap_hana_install_sapcar_file'
          being configured, so the SAPCAR executable in directory
          {{ sap_hana_install_software_directory }} will be determined automatically."
  when: sap_hana_install_sapcar_file is undefined

- name: Notify if the role is used without specifying SAR files
  debug:
    msg: "INFO: The role is used without variable 'sap_hana_install_sarfiles'
          being configured, so all SAR files in directory
          {{ sap_hana_install_software_directory }} will be extracted
          and used for the installation."
  when: sap_hana_install_sarfiles is undefined

- import_tasks: hana_exists.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: pre_install.yml

- import_tasks: hana_install.yml
  when: sap_hana_install_new_system|d(true)

- import_tasks: hana_addhosts.yml
  when: not sap_hana_install_new_system|d(true)

- import_tasks: post_install.yml
