---
################
# Password Facts
################

- name: SAP HANA Pre Install - Set password facts when using master password
  set_fact:
    sap_hana_install_sapadm_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_sidadm_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_db_system_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_ase_user_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_xs_org_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_lss_user_password: "{{ sap_hana_install_common_master_password }}"
    sap_hana_install_lss_backup_password: "{{ sap_hana_install_common_master_password }}"
  when: sap_hana_install_use_master_password == 'y'

################
# Prepare software path
################

- name: Prepare the HANA software for installation
  block:

    - name: SAP HANA Pre Install - Check availability of software directory '{{ sap_hana_install_software_directory }}'
      stat:
        path: "{{ sap_hana_install_software_directory }}"
      register: __sap_hana_install_register_stat_software_directory
      failed_when: no

    - name: SAP HANA Pre Install - Assert that the software directory exists
      assert:
        that: __sap_hana_install_register_stat_software_directory.stat.exists
        fail_msg: "FAIL: The software directory '{{ sap_hana_install_software_directory }}' does not exist!"
        success_msg: "PASS: The software directory '{{ sap_hana_install_software_directory }}' exist."

    - name: SAP HANA Pre Install - Change ownership of software directory '{{ sap_hana_install_software_directory }}'
      ansible.builtin.file:
        path: "{{ sap_hana_install_software_directory }}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: root
        group: root

    - name: SAP HANA Pre Install - Change ownership of HANA directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - '/hana'
        - '/hana/shared'
        - '/hana/log'
        - '/hana/data'

    - name: SAP HANA Pre Install - Get info about software extract directory '{{ sap_hana_install_software_extract_directory }}'
      stat:
        path: "{{ sap_hana_install_software_extract_directory }}"
      register: __sap_hana_install_register_stat_software_extract_directory
      failed_when: no

    - name: SAP HANA Pre Install - Find file 'hdblcm' if '{{ sap_hana_install_software_extract_directory }}' exists
      find:
        paths: "{{ sap_hana_install_software_extract_directory }}"
        recurse: yes
        file_type: file
        patterns: 'hdblcm'
      register: __sap_hana_install_register_find_hdblcm
      when: __sap_hana_install_register_stat_software_extract_directory.stat.exists

    - name: SAP HANA Pre Install - Set path of 'hdblcm' from successful find result
      block:

        - name: SAP HANA Pre Install - Set fact for 'hdblcm' installer directory if found initially
          set_fact:
            __sap_hana_install_fact_hdblcm_path: "{{ __sap_hana_install_register_find_hdblcm.files[0].path | dirname }}"

        - name: SAP HANA Pre Install - Show the full path name of file 'hdblcm'
          debug:
            msg: "Using file '{{ __sap_hana_install_fact_hdblcm_path + '/hdblcm' }}' for the installation of SAP HANA."

      when:
        - __sap_hana_install_register_stat_software_extract_directory.stat.exists
        - __sap_hana_install_register_find_hdblcm.files[0] is defined

    - name: SAP HANA Pre Install - Extract SAR files if file 'hdblcm' was not found initially
      block:

        - name: SAP HANA Pre Install - Run hdblcm prepare
          include_tasks: pre_install/hdblcm_prepare.yml

        - name: SAP HANA Pre Install - Display 'hdblcm' installer directory
          debug:
            var: __sap_hana_install_fact_hdblcm_path

        - name: SAP HANA Pre Install - Get info about '{{ __sap_hana_install_fact_hdblcm_path + '/hdblcm' }}'
          stat:
            path: "{{ __sap_hana_install_fact_hdblcm_path + '/hdblcm' }}"
          register: __sap_hana_install_register_stat_hdblcm
          failed_when: no

        - name: SAP HANA Pre Install - Assert that file 'hdblcm' is available
          assert:
            that: __sap_hana_install_register_stat_hdblcm.stat.exists
            fail_msg: "FAIL: File 'hdblcm' could not be found. Installation of SAP HANA is not possible."
            success_msg: "Using file '{{ __sap_hana_install_fact_hdblcm_path + '/hdblcm' }}' for the installation of SAP HANA."

      when: __sap_hana_install_register_find_hdblcm.files[0] is not defined

  when: sap_hana_install_new_system|d(true)

################
# Pre Install Steps
################

- name: SAP HANA Pre Install - Create temporary directory to store various files
  tempfile:
    state: directory
    suffix: hanaconfig
  register: __sap_hana_install_register_tmpdir

- name: SAP HANA Pre Install - Process HANA configfile template
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ __sap_hana_install_register_tmpdir.path }}/configfile.cfg"
    mode: '0644'
  register: __sap_hana_install_register_cftemplate
