---
- hosts: all
  become: true
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: ./vars/sample-variables-sap-hana-install.yml
  roles:
    - { role: ../roles/sap_hana_install }
