---
- hosts: all
  gather_facts: true
  serial: 1
  vars:
    sap_hypervisor_node_platform: redhat_ocp_virt

  tasks:
    - name: Include Role
      ansible.builtin.include_role:
        name: sap_hypervisor_node_preconfigure
