---
# The SAP ID must follow a strict format and not use reserved special values
# TODO: This check may be better placed in a SAP role earlier in the chain...
- name: "SAP HA Prepare Pacemaker - (SAP HANA) Validate SAP System ID"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_hana_sid | length == 3
      - sap_ha_pacemaker_cluster_hana_sid not in __sap_sid_prohibited
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Requires 'sap_ha_pacemaker_cluster_hana_sid' to be defined!
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

- name: "SAP HA Prepare Pacemaker - (SAP NetWeaver) Validate SAP System ID"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_netweaver_sid | length == 3
      - sap_ha_pacemaker_cluster_netweaver_sid not in __sap_sid_prohibited
    fail_msg: |
      Host type = {{ sap_ha_pacemaker_cluster_host_type }}
      Requires 'sap_ha_pacemaker_cluster_netweaver_sid' to be defined!
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas') | length > 0


# Verify that the user-defined VIP NIC device name exists on the system.
- name: "SAP HA Prepare Pacemaker - Verify that the custom NIC name exists"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_client_interface in ansible_interfaces
    fail_msg: "The interface '{{ sap_ha_pacemaker_cluster_vip_client_interface }}' does not exist on this system!"
  when:
    - sap_ha_pacemaker_cluster_vip_client_interface | length > 0

# Verify that an IP address for the VIP of the defined host type is defined.
- name: "SAP HA Prepare Pacemaker - (HANA primary) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_hana_primary_ip_address is defined
      - sap_ha_pacemaker_cluster_vip_hana_primary_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_hana_primary_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'hana') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver ASCS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_netweaver_ascs_ip_address is defined
      - sap_ha_pacemaker_cluster_vip_netweaver_ascs_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_netweaver_ascs_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver ERS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_netweaver_ers_ip_address is defined
      - sap_ha_pacemaker_cluster_vip_netweaver_ers_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_netweaver_ers_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_ascs_ers') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver PAS) Verify that the VIP is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_netweaver_pas_ip_address is defined
      - sap_ha_pacemaker_cluster_vip_netweaver_pas_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_netweaver_pas_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_pas') | length > 0

- name: "SAP HA Prepare Pacemaker - (NetWeaver AAS) Verify that the ERS VIP is defined"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_vip_netweaver_aas_ip_address is defined
      - sap_ha_pacemaker_cluster_vip_netweaver_aas_ip_address | length > 0
    fail_msg: "Host type = '{{ sap_ha_pacemaker_cluster_host_type }}', but 'sap_ha_pacemaker_cluster_vip_netweaver_aas_ip_address' is not defined."
  when:
    - sap_ha_pacemaker_cluster_host_type | select('search', 'nwas_abap_pas_aas') | length > 0
