---
# Requires: ansible 2.11
# Argument specifications in this separate file maintain backwards compatibility.
argument_specs:

# TODO: make 'ha_cluster' role variables the primary names, but allow aliases
# in the current role namespace

  main:
    short_description: SAP HA requirements
    options:

# Take this template and copy it to the desired place.
# Ideally sort by key (variable name) alphabetically.
#
#      sap_ha_cluster_
#        description:
#           -
#        type:
#        required: false
#        default:

      ha_cluster:
        description:
          - Optional host_vars parameter, if defined it must be set for each node.
          - Definition of node name and IP addresses to be used for the pacemaker cluster.
          - Required for resilient node communication by providing more than one corosync IP.
          - See https://github.com/linux-system-roles/ha_cluster/blob/master/README.md#nodes-names-and-addresses
        type: dict
        required: false
        options:
          node_name:
            description:
              - The name of the node in the cluster.
            default: <play host>
            type: str
          pcs_address:
            description:
              - An address used by pcs to communicate with the node.
              - Can be a name, FQDN or IP address and can contain a port.
            default: <play host>
            type: str
          corosync_addresses:
            description:
              - List of IP addresses used by Corosync.
              - All nodes must have the same number of addresses.
              - The order of the listed addresses  matters.
            type: list

      ha_cluster_cluster_name:
        description:
          - The name of the pacemaker cluster.
        type: str
        required: false
        default: my-cluster
        alias: sap_ha_cluster_cluster_name

      ha_cluster_hacluster_password:
        description:
          - The password of the `hacluster` user which is created during pacemaker installation.
        type: str
        required: true
        no_log: true
        alias: sap_hana_hacluster_password

      sap_ha_cluster_automated_register:
        description:
          - Define if a former primary should be re-registered automatically as secondary.
        type: bool
        required: false
        default: true

      sap_ha_cluster_create_config_dest:
        description:
          - The cluster resource configuration created by this role will be saved in a Yaml file in the current working directory.
          - Specify a path/filename to save the file elsewhere.
        type: str
        required: false
        default: sap_ha_cluster_resource_config.yml

      sap_ha_cluster_create_config_only:
        description:
          - Enable to only create an output of the parameters and values this role will use as input into the 'ha_cluster' role.
          - The output is saved in a variables file and used for individual execution of the 'ha_cluster' linux system role.
          - WARNING! This report may include sensitive details like secrets required for certain cluster resources!
        type: bool
        required: false
        default: false

      sap_ha_cluster_duplicate_primary_timeout:
        description:
          - Time difference needed between to primary time stamps, if a dual-primary situation occurs.
          - If the time difference is less than the time gap, then the cluster holds one or both instances in a "WAITING" status.
          - This is to give an admin a chance to react on a failover. A failed former primary will be registered after the time difference is passed.
        type: int
        required: false
        default: 900

      sap_ha_cluster_prefer_site_takeover:
        description:
          - Set to "false" if the cluster should first attempt to restart the instance on the same node.
          - When set to "true" (default) a failover to secondary will be initiated on resource failure.
        type: bool
        required: false
        default: true
        choices:
          - true
          - false

      sap_ha_cluster_replication_type:
        description:
          - The type of SAP HANA site replication across multiple hosts.
        type: str
        required: false
        default: none
        choices:
          - mtr
          - none

      sap_ha_cluster_sap_type:
        description:
          - The SAP landscape to be installed.
        type: str
        required: false
        default: scaleup
        choices:
          - scaleup
          - scaleout

      sap_hana_cluster_nodes:
        description:
          - List of cluster nodes and associated attributes (in dictionary format).
          - This is required for the srHook configuration.
        type: list
        required: true

      sap_hana_instance_number:
        description:
          - The instance number of the SAP HANA database which is role will configure in the cluster.
        type: str
        required: true
        alias: sap_ha_cluster_hana_instance_number

      sap_hana_sid:
        description:
          - The SAP System ID of the instance that will be configured in the cluster.
          - The SAP SID must follow SAP specifications - see SAP Note 1979280.
        type: str
        required: true
        alias: sap_ha_cluster_hana_sid

      sap_hana_vip:
        description:
          - Virtual floating IP for SAP HANA DB connections.
          - This IP will always run on the promoted HANA node.
        type: str
        required: true
