---
# Requires: ansible 2.11
# Argument specifications in this separate file maintain backwards compatibility.
argument_specs:

# TODO: make 'ha_cluster' role variables the primary names, but allow aliases
# in the current role namespace

  main:
    short_description: SAP HA requirements
    options:

# Take this template and copy it to the desired place.
# Add content and remove placeholders that are not needed.
# Ideally sort by key (variable name) alphabetically.
#
#      sap_ha_cluster_
#        alias:
#        default:
#        description:
#           -
#        required: false
#        type:
#        options: # additional options for lists and dicts
#          <param>:
#            description:
#            ...

      ha_cluster:
        description:
          - Optional host_vars parameter, if defined it must be set for each node.
          - Definition of node name and IP addresses to be used for the pacemaker cluster.
          - Required for resilient node communication by providing more than one corosync IP.
          - See https://github.com/linux-system-roles/ha_cluster/blob/master/README.md#nodes-names-and-addresses
        required: false
        type: dict
        options:
          corosync_addresses:
            default: <primary ip>
            description:
              - List of IP addresses used by Corosync.
              - All nodes must have the same number of addresses.
              - The order of the listed addresses  matters.
            type: list
          node_name:
            default: <play host>
            description:
              - The name of the node in the cluster.
            type: str
          pcs_address:
            default: <play host>
            description:
              - An address used by pcs to communicate with the node.
              - Can be a name, FQDN or IP address and can contain a port.
            type: str

      ha_cluster_cluster_name:
        alias: sap_ha_cluster_cluster_name
        default: my-cluster
        description:
          - The name of the pacemaker cluster.
        required: false
        type: str

      ha_cluster_hacluster_password:
        alias: sap_hana_hacluster_password
        description:
          - The password of the `hacluster` user which is created during pacemaker installation.
        no_log: true
        required: true
        type: str

      sap_ha_cluster_aws_region:
        description:
          - The AWS region in which the instances to be used for the cluster setup are located.
          - Required for cluster nodes setup on Amazon cloud.
        required: false
        type: str

      sap_ha_cluster_aws_access_key_id:
        description:
          - AWS access key to allow control of instances (for example for fencing operations).
          - Required for cluster nodes setup on Amazon cloud.
        required: false
        type: str

      sap_ha_cluster_aws_secret_access_key:
        description:
          - AWS secret key, paired with the access key for instance control.
          - Required for cluster nodes setup on Amazon cloud.
        required: false
        type: str

      sap_ha_cluster_create_config_dest:
        default: sap_ha_cluster_resource_config.yml
        description:
          - The cluster resource configuration created by this role will be saved in a Yaml file in the current working directory.
          - Specify a path/filename to save the file elsewhere.
        required: false
        type: str

      sap_ha_cluster_create_config_only:
        default: false
        description:
          - Enable to only create an output of the parameters and values this role will use as input into the 'ha_cluster' role.
          - The output is saved in a variables file and used for individual execution of the 'ha_cluster' linux system role.
          - WARNING! This report may include sensitive details like secrets required for certain cluster resources!
        required: false
        type: bool

      sap_ha_cluster_fence_power_timeout:
        default: 240
        description:
          - STONITH resource parameter to test X seconds for status change after ON/OFF.
        required: false
        type: int

      sap_ha_cluster_fence_reboot_retries:
        default: 4
        description:
          - STONITH resource parameter to define how often it retries to restart a node.
        required: false
        type: int

      sap_ha_cluster_fence_reboot_timeout:
        default: 400
        description:
          - STONITH resource parameter to define after which timeout a node restart is returned as failed.
        required: false
        type: int

      sap_ha_cluster_hana_automated_register:
        default: true
        description:
          - Define if a former primary should be re-registered automatically as secondary.
        required: false
        type: bool

      sap_ha_cluster_hana_duplicate_primary_timeout:
        default: 900
        description:
          - Time difference needed between to primary time stamps, if a dual-primary situation occurs.
          - If the time difference is less than the time gap, then the cluster holds one or both instances in a "WAITING" status.
          - This is to give an admin a chance to react on a failover. A failed former primary will be registered after the time difference is passed.
        required: false
        type: int

      sap_ha_cluster_hana_prefer_site_takeover:
        choices:
          - true
          - false
        default: true
        description:
          - Set to "false" if the cluster should first attempt to restart the instance on the same node.
          - When set to "true" (default) a failover to secondary will be initiated on resource failure.
        required: false
        type: bool

      sap_ha_cluster_hana_resource_name:
        default: "SAPHana_<SID>_<Instance Number>"
        description:
          - Customize the cluster resource name of the SAP HANA DB resource.
        required: false
        type: str

      sap_ha_cluster_hana_topology_resource_name:
        default: "SAPHanaTopology_<SID>_<Instance Number>"
        description:
          - Customize the cluster resource name of the SAP HANA Topology resource.
        required: false
        type: str

      sap_ha_cluster_replication_type:
        choices:
          - mtr
          - none
        default: none
        description:
          - The type of SAP HANA site replication across multiple hosts.
        required: false
        type: str

      sap_ha_cluster_sap_type:
        choices:
          - scaleup
          - scaleout
        default: scaleup
        description:
          - The SAP landscape to be installed.
        required: false
        type: str

      sap_hana_cluster_nodes:
        description:
          - List of cluster nodes and associated attributes (in dictionary format).
          - This is required for the srHook configuration.
        elements: str
        required: true
        type: list

      sap_hana_instance_number:
        alias: sap_ha_cluster_hana_instance_number
        description:
          - The instance number of the SAP HANA database which is role will configure in the cluster.
        required: true
        type: str

      sap_hana_sid:
        alias: sap_ha_cluster_hana_sid
        description:
          - The SAP System ID of the instance that will be configured in the cluster.
          - The SAP SID must follow SAP specifications - see SAP Note 1979280.
        required: true
        type: str

      sap_hana_vip:
        description:
          - Virtual floating IP for SAP HANA DB connections.
          - This IP will always run on the promoted HANA node.
        required: true
        type: dict
        options:
          primary:
            aliases:
              - main
              - promoted
            description:
              - At least one Virtual IP is required to always reach the promoted SAP HANA DB.
            required: true
            type: str
          secondary:
            aliases:
              - unpromoted
              - readonly
            description:
              - An additional VIP can be used to run on a secondary node for read-only DB access.
            required: false
            type: str
