---
# Requires: ansible 2.11
# Argument specifications in this separate file maintain backwards compatibility.
argument_specs:

# TODO:
# - add 'ha_cluster' native role variables that are supported by this
# sap_ha_cluster wrapper role (meaning, that are input parameters when
# including 'ha_cluster'
# - make 'ha_cluster' role variables the primary names, but allow
# alias variable names in the current role namespace

  main:
    short_description: SAP HA requirements
    options:
      sap_hana_sid:
        description:
          - The SAP System ID of the instance that will be configured in the cluster.
          - The SAP SID must follow SAP specifications - see SAP Note 1979280.
        type: str
        required: true
        alias: sap_ha_cluster_hana_sid

      sap_hana_instance_number:
        description: The instance number of the SAP HANA database which is role will configure in the cluster.
        type: str
        required: true
        alias: sap_ha_cluster_hana_instance_number

      ha_cluster_cluster_name:
        description: The name of the pacemaker cluster.
        type: str
        required: false
        default: my-cluster
        alias: sap_ha_cluster_cluster_name

      ha_cluster_hacluster_password:
        description: The password of the `hacluster` user which is created during pacemaker installation.
        type: str
        required: true
        no_log: true
        alias: sap_hana_hacluster_password

      sap_hana_vip:
        description:
          - Virtual floating IP for SAP HANA DB connections.
          - This IP always will always run on the promoted HANA node.
        type: str
        required: true

      sap_ha_cluster_sap_type:
        description: The SAP landscape to be installed.
        type: str
        required: false
        default: scaleup
        choices:
          - scaleup
          - scaleout

      sap_ha_cluster_replication_type:
        description: The type of SAP HANA site replication across multiple hosts.
        type: str
        required: false
        default: none
        choices:
          - mtr
          - none

      sap_ha_cluster_prefer_site_takeover:
        description: Set to "false" if the cluster should first attempt to restart the instance on the same node. When set to "true" (default) a failover to secondary will be initiated on resource failure.
        type: bool
        required: false
        default: true
        choices:
          - true
          - false

      sap_ha_cluster_automated_register:
        description: Define if a former primary should be re-registered automatically as secondary.
        type: bool
        required: false
        default: true

      sap_ha_cluster_duplicate_primary_timeout:
        description: Time difference needed between to primary time stamps, if a dual-primary situation occurs. If the time difference is less than the time gap, then the cluster holds one or both instances in a "WAITING" status. This is to give an admin a chance to react on a failover. A failed former primary will be registered after the time difference is passed. After this registration to the new primary all data will be overwritten by the system replication.
        type: int
        required: false
        default: 900

#      sap_ha_cluster_
#        description:
#        type:
#        required: false
#        default:
