name: Ansible Lint for sap_hana_rhv_guest

on: 
  push: 
    paths: 
      - 'roles/sap_hana_rhv_guest/**'
  pull_request:
    paths: 
      - 'roles/sap_hana_rhv_guest/**'
jobs:
  ansible-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
          ./roles/sap_hana_rhv_guest
        override-deps: |
          ansible==5.3.0
          ansible-lint==5.3.2

# Static: use Ansible Community Edition 4.8.0, with lowest compatible Ansible Core 2.11.6 and use Ansible-lint 5.2.1
