# Worflow for ansible-lint

name: ansible-lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: pip3 install ansible ansible-lint

#      - name: Install collection dependencies
#        run: ansible-galaxy collection install community.general

      - name: Move the collection to the correct location - Create new directory
        run: mkdir -p /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Move the collection
        working-directory: /home/runner/
        run: mv /home/runner/work/community.sap_install/community.sap_install /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Rename the directory
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/community.sap_install /home/runner/.ansible/collections/ansible_collections/community/sap_install

      - name: Run ansible-lint
        working-directory: /home/runner/.ansible/collections/ansible_collections/community/sap_install
        run: ansible-lint

      - name: Move the collection to its previous location
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/sap_install /home/runner/work/community.sap_install/community.sap_install
