# Worflow for ansible-test sanity tests

name: ansible-test sanity

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: pip3 install yamllint ansible ansible-lint

#      - name: Install collection dependencies
#        run: ansible-galaxy collection install community.general

      - name: List directory /home/runner/work/
        working-directory: /home/runner/
        run: ls -al /home/runner/work/

      - name: List directory /home/runner/work/_actions
        working-directory: /home/runner/
        run: ls -al /home/runner/work/_actions

      - name: List directory /home/runner/work/community.sap_install
        working-directory: /home/runner/
        run: ls -al /home/runner/work/community.sap_install

      - name: List directory /home/runner/work/community.sap_install/community.sap_install
        working-directory: /home/runner/
        run: ls -al /home/runner/work/community.sap_install/community.sap_install

      - name: Move the collection to the correct location - Create new directory
        run: mkdir -p /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Move the collection
        working-directory: /home/runner/
        run: mv /home/runner/work/community.sap_install/community.sap_install /home/runner/.ansible/collections/ansible_collections/community

      - name: List directory /home/runner/.ansible/collections/ansible_collections/community
        working-directory: /home/runner/
        run: ls -al /home/runner/.ansible/collections/ansible_collections/community

      - name: Move the collection to the correct location - Rename the directory
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/community.sap_install /home/runner/.ansible/collections/ansible_collections/community/sap_install

      - name: List directory /home/runner/.ansible/collections/ansible_collections/community
        working-directory: /home/runner/
        run: ls -al /home/runner/.ansible/collections/ansible_collections/community

      - name: List directory /home/runner/.ansible/collections/ansible_collections/community/sap_install
        working-directory: /home/runner/
        run: ls -al /home/runner/.ansible/collections/ansible_collections/community/sap_install

      - name: List directory /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests
        working-directory: /home/runner/
        run: ls -al /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests

      - name: List directory /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests/sanity
        working-directory: /home/runner/
        run: ls -al /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests/sanity

      - name: Show the content of file /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests/sanity/ignore-2.13.txt
        working-directory: /home/runner/
        run: cat /home/runner/.ansible/collections/ansible_collections/community/sap_install/tests/sanity/ignore-2.13.txt

      - name: Run sanity tests
        working-directory: /home/runner/.ansible/collections/ansible_collections/community/sap_install
        run: ansible-test sanity

      - name: Move the collection to its previous location
        working-directory: /home/runner/
        run: mv /home/runner/.ansible/collections/ansible_collections/community/sap_install /home/runner/work/community.sap_install/community.sap_install
