---

# Workflow for ansible-lint of a role

name: ansible-lint of the role sap_ha_install_hana_hsr

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_ha_install_hana_hsr/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_ha_install_hana_hsr/**'

jobs:
  ansible-lint:
    call-ansible-lint-with-role:
        uses: sap-linuxlab/community.sap_install/.github/workflows/ansible-lint-sap_reusable_workflow.yml@main
        with:
          role: sap_ha_install_hana_hsr

