---

# Workflow for ansible-lint of a role

name: ansible-lint of the role sap_general_preconfigure

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_general_preconfigure/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_general_preconfigure/**'

jobs:
  ansible-lint:
    call-ansible-lint-with-role:
        uses: sap-linuxlab/community.sap_install/.github/workflows/ansible-lint-sap_reusable_workflow.yml@main
        with:
          role: sap_general_preconfigure

