# Worflow for ansible-test sanity tests

name: ansible-test sanity

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: pip3 install yamllint ansible ansible-lint

      - name: Install collection dependencies
        run: ansible-galaxy collection install community.general

      - name: Move the collection to the correct location
        run: mkdir -p /home/runner/.ansible/collections/ansible_collections/community && mv /home/runner/work/community.sap_install /home/runner/.ansible/collections/ansible_collections/community/sap_install
#        run: mkdir -p /home/runner/.ansible/collections/ansible_collections/community && ln -s /home/runner/work/community.sap_install /home/runner/.ansible/collections/ansible_collections/community/sap_install

      - name: Run sanity tests
        working-directory: /home/runner/.ansible/collections/ansible_collections/community/sap_install
        run: ansible-test sanity

      - name: Move the collection to its previous location
        run: rm /home/runner/.ansible/collections/ansible_collections/community/sap_install

#      - name: Perform sanity testing with ansible-test
#        uses: ansible-community/ansible-test-gh-action@release/v1
#        with:
#          ansible-core-version: stable-2.11
#          testing-type: sanity
