---

name: Check outdated dependencies

on:
  schedule:
    - cron: '0 7 1,15 * *'

  workflow_dispatch:

jobs:
  check_outdate_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@main

      - name: Check workflow dependencies 
        uses: ./workflows/check_outdate_deps
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENT_FILE: "requirements-workflow.txt"
